package mysql_data_link.Passoin;







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
import mysql_data_link.Doctor.Frm_Doctor_service;
import mysql_data_link.Doctor.Frm_Doctor_imployee;
import mysql_data_link.Doctor.Frm_doctorData;
import Reports.*;
   import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JFrame;
import mysql_data_link.ZeftawyTools.OtherMethods;
import projict_Class.Projmethods;
    import Store_Manag.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mysql_data_link.ZeftawyTools.Toast;
   
public class Frm_Poj_Main extends javax.swing.JFrame {
  Projmethods pr = new Projmethods();
     AmanPasDatabse_Visit_table visit_table = new AmanPasDatabse_Visit_table(pr.ConnectToPasDataBase());
       String Pas_id;
   
    /**
     * Creates new form 
     */
    public  Frm_Poj_Main()  {
            initComponents();
        Tbp_DataSet.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
      pnl__Doctor.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            pnl_Pas_Files.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
      pnl_Reports.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
      pnl_Setting.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
      pnl_Store_Manag.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
      
            
            load();
 
    }
    boolean loading = false;
    void load (){
   
     
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
  OtherMethods o = new OtherMethods();
        o.JTableformatWait(jTable1);
      loading = true ;
    try{  jTable1.setModel(visit_table.showInmainTable());
    }catch(Exception ex ){}
    loading = false ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTpb_DataSet = new javax.swing.JPanel();
        Tbp_DataSet = new javax.swing.JTabbedPane();
        pnl__Doctor = new javax.swing.JPanel();
        a_imgabutton3 = new projict_Class.A_imgabutton();
        a_imgabutton5 = new projict_Class.A_imgabutton();
        a_imgabutton6 = new projict_Class.A_imgabutton();
        a_imgabutton7 = new projict_Class.A_imgabutton();
        a_imgabutton15 = new projict_Class.A_imgabutton();
        pnl_Pas_Files = new javax.swing.JPanel();
        a_imgabutton8 = new projict_Class.A_imgabutton();
        a_imgabutton9 = new projict_Class.A_imgabutton();
        a_imgabutton10 = new projict_Class.A_imgabutton();
        a_imgabutton4 = new projict_Class.A_imgabutton();
        a_imgabutton16 = new projict_Class.A_imgabutton();
        pnl_Store_Manag = new javax.swing.JPanel();
        a_imgabutton17 = new projict_Class.A_imgabutton();
        a_imgabutton18 = new projict_Class.A_imgabutton();
        pnl_Reports = new javax.swing.JPanel();
        a_imgabutton11 = new projict_Class.A_imgabutton();
        a_imgabutton19 = new projict_Class.A_imgabutton();
        a_imgabutton20 = new projict_Class.A_imgabutton();
        pnl_Setting = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        a_imgabutton12 = new projict_Class.A_imgabutton();
        a_imgabutton13 = new projict_Class.A_imgabutton();
        a_imgabutton14 = new projict_Class.A_imgabutton();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_vist = new projict_Class.TxTf();
        txt_pas = new projict_Class.TxTf();
        txt_doc = new projict_Class.TxTf();
        txt_value = new projict_Class.TxTf();
        txt_exp = new projict_Class.TxTf();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        PnlTpb_DataSet.setBackground(new java.awt.Color(255, 255, 255));
        PnlTpb_DataSet.setName("PnlTpb_DataSet"); // NOI18N

        Tbp_DataSet.setBackground(new java.awt.Color(0, 153, 153));
        Tbp_DataSet.setName("Tbp_DataSet"); // NOI18N

        pnl__Doctor.setBackground(new java.awt.Color(204, 204, 204));
        pnl__Doctor.setName("pnl__Doctor"); // NOI18N

        a_imgabutton3.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton3.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton3.setName("a_imgabutton3"); // NOI18N
        a_imgabutton3.setText("بيانات الطبيب");
        a_imgabutton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton3MouseClicked(evt);
            }
        });

        a_imgabutton5.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton5.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton5.setName("a_imgabutton5"); // NOI18N
        a_imgabutton5.setText("المتعاقدين مع الطبيب");
        a_imgabutton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton5MouseClicked(evt);
            }
        });

        a_imgabutton6.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton6.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton6.setName("a_imgabutton6"); // NOI18N
        a_imgabutton6.setText("الخدمات والعيادة");
        a_imgabutton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton6MouseClicked(evt);
            }
        });

        a_imgabutton7.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton7.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton7.setName("a_imgabutton7"); // NOI18N
        a_imgabutton7.setText("شركة التأمين");
        a_imgabutton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton7MouseClicked(evt);
            }
        });

        a_imgabutton15.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton15.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton15.setName("a_imgabutton15"); // NOI18N
        a_imgabutton15.setText("العاملين");
        a_imgabutton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl__DoctorLayout = new javax.swing.GroupLayout(pnl__Doctor);
        pnl__Doctor.setLayout(pnl__DoctorLayout);
        pnl__DoctorLayout.setHorizontalGroup(
            pnl__DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl__DoctorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(a_imgabutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a_imgabutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        pnl__DoctorLayout.setVerticalGroup(
            pnl__DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl__DoctorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl__DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a_imgabutton15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Tbp_DataSet.addTab("الطبيب والعيادة", pnl__Doctor);

        pnl_Pas_Files.setBackground(new java.awt.Color(204, 204, 204));
        pnl_Pas_Files.setName("pnl_Pas_Files"); // NOI18N

        a_imgabutton8.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton8.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton8.setName("a_imgabutton8"); // NOI18N
        a_imgabutton8.setText("حساب شركة التأمين");
        a_imgabutton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton8MouseClicked(evt);
            }
        });

        a_imgabutton9.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton9.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton9.setName("a_imgabutton9"); // NOI18N
        a_imgabutton9.setText("كشف حساب المريض");
        a_imgabutton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton9MouseClicked(evt);
            }
        });

        a_imgabutton10.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton10.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton10.setName("a_imgabutton10"); // NOI18N
        a_imgabutton10.setText("عمليات وخدمات");
        a_imgabutton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton10MouseClicked(evt);
            }
        });

        a_imgabutton4.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton4.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton4.setName("a_imgabutton4"); // NOI18N
        a_imgabutton4.setText("F2 بيانات المرضى");
        a_imgabutton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton4MouseClicked(evt);
            }
        });

        a_imgabutton16.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton16.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton16.setName("a_imgabutton16"); // NOI18N
        a_imgabutton16.setText("تقارير طبية للمريض");

        javax.swing.GroupLayout pnl_Pas_FilesLayout = new javax.swing.GroupLayout(pnl_Pas_Files);
        pnl_Pas_Files.setLayout(pnl_Pas_FilesLayout);
        pnl_Pas_FilesLayout.setHorizontalGroup(
            pnl_Pas_FilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pas_FilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_imgabutton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(a_imgabutton10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        pnl_Pas_FilesLayout.setVerticalGroup(
            pnl_Pas_FilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pas_FilesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Pas_FilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a_imgabutton16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tbp_DataSet.addTab("ملفات المرضى", pnl_Pas_Files);

        pnl_Store_Manag.setBackground(new java.awt.Color(204, 204, 204));
        pnl_Store_Manag.setName("pnl_Store_Manag"); // NOI18N

        a_imgabutton17.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton17.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton17.setName("a_imgabutton17"); // NOI18N
        a_imgabutton17.setText("تسجيل الأصناف بالمخازن");
        a_imgabutton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton17MouseClicked(evt);
            }
        });

        a_imgabutton18.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton18.setMousemoveBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton18.setName("a_imgabutton18"); // NOI18N
        a_imgabutton18.setText("تسجيل حركة المخازن");
        a_imgabutton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_Store_ManagLayout = new javax.swing.GroupLayout(pnl_Store_Manag);
        pnl_Store_Manag.setLayout(pnl_Store_ManagLayout);
        pnl_Store_ManagLayout.setHorizontalGroup(
            pnl_Store_ManagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Store_ManagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_imgabutton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_imgabutton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        pnl_Store_ManagLayout.setVerticalGroup(
            pnl_Store_ManagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Store_ManagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Store_ManagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a_imgabutton18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Tbp_DataSet.addTab("إدارة المخزون", pnl_Store_Manag);

        pnl_Reports.setBackground(new java.awt.Color(204, 204, 204));
        pnl_Reports.setName("pnl_Reports"); // NOI18N

        a_imgabutton11.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton11.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton11.setName("a_imgabutton11"); // NOI18N
        a_imgabutton11.setText("تقارير ملفات المرضى");
        a_imgabutton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton11MouseClicked(evt);
            }
        });

        a_imgabutton19.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton19.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton19.setName("a_imgabutton19"); // NOI18N
        a_imgabutton19.setText("تقارير زيارات المرضى");
        a_imgabutton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton19MouseClicked(evt);
            }
        });

        a_imgabutton20.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton20.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton20.setName("a_imgabutton20"); // NOI18N
        a_imgabutton20.setText("تقارير حسابات المرضى");
        a_imgabutton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_imgabutton20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_ReportsLayout = new javax.swing.GroupLayout(pnl_Reports);
        pnl_Reports.setLayout(pnl_ReportsLayout);
        pnl_ReportsLayout.setHorizontalGroup(
            pnl_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_imgabutton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_imgabutton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_imgabutton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(596, Short.MAX_VALUE))
        );
        pnl_ReportsLayout.setVerticalGroup(
            pnl_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ReportsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a_imgabutton20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Tbp_DataSet.addTab("التقارير", pnl_Reports);

        pnl_Setting.setBackground(new java.awt.Color(204, 204, 204));
        pnl_Setting.setName("pnl_Setting"); // NOI18N

        javax.swing.GroupLayout pnl_SettingLayout = new javax.swing.GroupLayout(pnl_Setting);
        pnl_Setting.setLayout(pnl_SettingLayout);
        pnl_SettingLayout.setHorizontalGroup(
            pnl_SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        pnl_SettingLayout.setVerticalGroup(
            pnl_SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        Tbp_DataSet.addTab("الاعدادات", pnl_Setting);

        javax.swing.GroupLayout PnlTpb_DataSetLayout = new javax.swing.GroupLayout(PnlTpb_DataSet);
        PnlTpb_DataSet.setLayout(PnlTpb_DataSetLayout);
        PnlTpb_DataSetLayout.setHorizontalGroup(
            PnlTpb_DataSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tbp_DataSet)
        );
        PnlTpb_DataSetLayout.setVerticalGroup(
            PnlTpb_DataSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tbp_DataSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setName("jPanel2"); // NOI18N

        a_imgabutton12.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton12.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton12.setName("a_imgabutton12"); // NOI18N
        a_imgabutton12.setText("سداد الحساب");

        a_imgabutton13.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton13.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton13.setName("a_imgabutton13"); // NOI18N
        a_imgabutton13.setText("حجز الزيارة القادمة");

        a_imgabutton14.setDefBackground(new java.awt.Color(204, 204, 204));
        a_imgabutton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a_imgabutton14.setMousemoveBackground(new java.awt.Color(153, 153, 153));
        a_imgabutton14.setName("a_imgabutton14"); // NOI18N
        a_imgabutton14.setText("تحويل لطبيب اخر");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_imgabutton14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_imgabutton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_imgabutton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_imgabutton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_imgabutton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAdd.setText("إضافة");
        btnAdd.setBorder(null);
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnDelete.setText("الغاء الحجز");
        btnDelete.setBorder(null);
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSearch.setText("ادخال للطبيب");
        btnSearch.setBorder(null);
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch))
                .addContainerGap())
        );

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.setName("jPanel3"); // NOI18N

        txt_vist.setName("txt_vist"); // NOI18N

        txt_pas.setBackground(new java.awt.Color(255, 204, 204));
        txt_pas.setName("txt_pas"); // NOI18N

        txt_doc.setName("txt_doc"); // NOI18N

        txt_value.setName("txt_value"); // NOI18N

        txt_exp.setName("txt_exp"); // NOI18N

        jLabel2.setText("اسم المريض");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("رقم الزيارة");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("الطبيب");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("نوع الكشف");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("قيمة الكشف");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_vist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_doc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_exp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_vist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTpb_DataSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTpb_DataSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
Frm_pasShowData pData = new Frm_pasShowData();
pData.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.println("11111");
   System.out.println("deativated");
        load();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      try {
          visit_table.Drob_ELahgz(Pas_id);
            load();
            Toast t = new Toast();
            t.Showtoast("تم الحذف");
          // TODO add your handling code here:
      } catch (SQLException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      try {
        
          visit_table.Update_newVisit(visit_table.DOCTOR_INTER, Pas_id);
          load();
          // TODO add your handling code here:
      } catch (SQLException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void a_imgabutton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton3MouseClicked
       Frm_doctorData f=new Frm_doctorData();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton3MouseClicked

    private void a_imgabutton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton5MouseClicked
      //  Frm_ContDoctor f=new Frm_ContDoctor();
      //f.setVisible(true);
       
    }//GEN-LAST:event_a_imgabutton5MouseClicked

    private void a_imgabutton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton6MouseClicked
        Frm_Doctor_service f=new Frm_Doctor_service();
        f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton6MouseClicked

    private void a_imgabutton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton7MouseClicked
 
   
    }//GEN-LAST:event_a_imgabutton7MouseClicked

    private void a_imgabutton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton15MouseClicked
        Frm_Doctor_imployee f=new Frm_Doctor_imployee();
        f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton15MouseClicked

    private void a_imgabutton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton4MouseClicked
        Frm_pasiont_data f=new Frm_pasiont_data();
        f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton4MouseClicked

    private void a_imgabutton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton10MouseClicked
       Frm_insert_opeSrv f=new Frm_insert_opeSrv();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton10MouseClicked

    private void a_imgabutton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton9MouseClicked
       Frm_PasRevenue f=new Frm_PasRevenue();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton9MouseClicked

    private void a_imgabutton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton17MouseClicked
       Frm_storage_categorisRecord f=new Frm_storage_categorisRecord();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton17MouseClicked

    private void a_imgabutton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton18MouseClicked
     //  Frm_storageMovement f=new Frm_storageMovement();
    //   f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton18MouseClicked

    private void a_imgabutton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton8MouseClicked
        Frm_insuranceCompany f=new Frm_insuranceCompany();
        f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton8MouseClicked

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

        System.out.println("deativated");
        load();
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// if (loading ){return ;}
        
        int row = jTable1.rowAtPoint(evt.getPoint());

        int col = jTable1.columnAtPoint(evt.getPoint());

    String valueInCell = (String)jTable1.getValueAt(row, col);

        String id =  visit_table.datashw.getvalue(row, visit_table.ID);
String name = visit_table.datashw.getvalue(row, visit_table.pasName);
    System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
        Pas_id = id;
String Pas_Name = name;
String Doctorname , Novist  , Examtype , Exampvalue;
Doctorname  =visit_table.datashw.getvalue(row, visit_table.Doctor); 
//Novist  =visit_table.datashw.getvalue(row, visit_table.;
Examtype  =visit_table.datashw.getvalue(row, visit_table.ExamType);
Exampvalue  =visit_table.datashw.getvalue(row, visit_table.ExamValue);

txt_pas.setText(Pas_Name);
txt_doc.setText(Doctorname);
txt_exp.setText(Examtype);
txt_value.setText(Exampvalue);

      try {
          Novist  =visit_table.getVisetNom(id)+"";
         txt_vist.setText(Novist);
          /* try {
          
          visit_table.LoadSelected_pas(id);
          // TODO add your handling code here:
          }catch(Exception e ){}
          */
          
          
          // TODO add your handling code here:
      } catch (SQLException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Poj_Main.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jTable1MouseClicked

    private void a_imgabutton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton11MouseClicked
       Frm_report_pasFile f=new Frm_report_pasFile();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton11MouseClicked

    private void a_imgabutton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton19MouseClicked
       Frm_repert_pasVist f=new Frm_repert_pasVist();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton19MouseClicked

    private void a_imgabutton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_imgabutton20MouseClicked
       Frm_report_pasRevenue f=new Frm_report_pasRevenue();
       f.setVisible(true);
    }//GEN-LAST:event_a_imgabutton20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Poj_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Poj_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Poj_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Poj_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Poj_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTpb_DataSet;
    private javax.swing.JTabbedPane Tbp_DataSet;
    private projict_Class.A_imgabutton a_imgabutton10;
    private projict_Class.A_imgabutton a_imgabutton11;
    private projict_Class.A_imgabutton a_imgabutton12;
    private projict_Class.A_imgabutton a_imgabutton13;
    private projict_Class.A_imgabutton a_imgabutton14;
    private projict_Class.A_imgabutton a_imgabutton15;
    private projict_Class.A_imgabutton a_imgabutton16;
    private projict_Class.A_imgabutton a_imgabutton17;
    private projict_Class.A_imgabutton a_imgabutton18;
    private projict_Class.A_imgabutton a_imgabutton19;
    private projict_Class.A_imgabutton a_imgabutton20;
    private projict_Class.A_imgabutton a_imgabutton3;
    private projict_Class.A_imgabutton a_imgabutton4;
    private projict_Class.A_imgabutton a_imgabutton5;
    private projict_Class.A_imgabutton a_imgabutton6;
    private projict_Class.A_imgabutton a_imgabutton7;
    private projict_Class.A_imgabutton a_imgabutton8;
    private projict_Class.A_imgabutton a_imgabutton9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnl_Pas_Files;
    private javax.swing.JPanel pnl_Reports;
    private javax.swing.JPanel pnl_Setting;
    private javax.swing.JPanel pnl_Store_Manag;
    private javax.swing.JPanel pnl__Doctor;
    private projict_Class.TxTf txt_doc;
    private projict_Class.TxTf txt_exp;
    private projict_Class.TxTf txt_pas;
    private projict_Class.TxTf txt_value;
    private projict_Class.TxTf txt_vist;
    // End of variables declaration//GEN-END:variables





}
