package mysql_data_link.Passoin;




import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Z_connection;
import org.w3c.dom.events.DocumentEvent;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class pnl_ope_Srv extends javax.swing.JPanel
implements  IDataEntery{
AmanPasDatabse_PasdataTable pasdata;
AmanPasDatabse_ope_srv pas_opeSrv;
     String Pas_id = "1" , Pas_Name  ;
public boolean isLoad=true;
    String file_id = 1+"";
    public pnl_ope_Srv() {
        initComponents();
         
        try{
        loadData();
} catch(Exception e){System.out.println(e);}
    }
    
    void loadData() throws SQLException, ParseException{
    if(isLoad){
        Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
       pas_opeSrv =new AmanPasDatabse_ope_srv(z_connection);
     pasdata = new AmanPasDatabse_PasdataTable(z_connection);
    OtherMethods o = new OtherMethods(); o.JTableformat(Tble_Show_dataFile);
     Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview_name(""));
}
    }
  
    
    void insert(){
        try{
   pas_opeSrv.insetNewOperation();}
        catch(Exception e){System.out.println(e);}
    }
    
    void update(){
    try{
    pas_opeSrv.UpdateDataOperation(Pas_id);
    }catch(Exception e){System.out.println(e);}
    }

    void delete(){
    try{
    pas_opeSrv.DeleteDataOperation(Pas_id);
    }
    catch(Exception e){System.out.println(e);}
    }

         
             


     
    
     void pas_SaarchName(String s) throws SQLException, ParseException{
         try {
             Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
         } catch (SQLException ex) {
             Logger.getLogger(pnl_ope_Srv.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ParseException ex) {
             Logger.getLogger(pnl_ope_Srv.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_opeType = new javax.swing.JLabel();
        Lbl_AnethDoctor = new javax.swing.JLabel();
        Lbl_opeDoctor = new javax.swing.JLabel();
        Lbl_AssistDoctor = new javax.swing.JLabel();
        Lbl_opeCost = new javax.swing.JLabel();
        Lbl_AnesthType = new javax.swing.JLabel();
        Lbl_opeNurse = new javax.swing.JLabel();
        Lbl_opeTechnical = new javax.swing.JLabel();
        LblPas_ID = new javax.swing.JLabel();
        LblPas_Name = new javax.swing.JLabel();
        LblOpe_Date = new javax.swing.JLabel();
        LblConrt_Doc = new javax.swing.JLabel();
        txtPas_ID = new projict_Class.TxTf();
        txtPas_Name = new projict_Class.TxTf();
        txtOpe_Date = new projict_Class.TxTf();
        txt_opeType = new projict_Class.TxTf();
        txtConvrt_Doc = new projict_Class.TxTf();
        txt_opeCost = new projict_Class.TxTf();
        txtAneths_Doctor = new projict_Class.TxTf();
        txtope_Doctor = new projict_Class.TxTf();
        txtAnthes_Type = new projict_Class.TxTf();
        txtope_Nurse = new projict_Class.TxTf();
        txtAssist_Doctor = new projict_Class.TxTf();
        txtope_Technical = new projict_Class.TxTf();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tble_ope_Data = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTotal_Revenue = new javax.swing.JTextField();
        LblNotce_Doc = new javax.swing.JLabel();
        txtNotice_Doc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tble_Show_dataFile = new javax.swing.JTable();

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        jButton6.setText("اضافة جديد");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("تعديل ملف");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data))
                .addGap(2, 2, 2))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addGap(7, 7, 7)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSearch_ID_Pas_Data)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("بيانات العمليات :");

        Lbl_opeType.setText("نوع العملية :");

        Lbl_AnethDoctor.setText("طبيب التخدير :");

        Lbl_opeDoctor.setText("طبيب العملية  :");

        Lbl_AssistDoctor.setText("الطبيب المساعد :");

        Lbl_opeCost.setText("تكلفة العمليات :");

        Lbl_AnesthType.setText("نوع التخدير :");

        Lbl_opeNurse.setText("ممرضة العمليات :");

        Lbl_opeTechnical.setText("فنى عمليات :");

        LblPas_ID.setText("رقم المريض :");

        LblPas_Name.setText("اسم المريض :");

        LblOpe_Date.setText("تاريخ العملية :");

        LblConrt_Doc.setText("طبيب التحويل");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_opeType, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txt_opeCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnthes_Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtope_Nurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtope_Technical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_opeTechnical)
                            .addComponent(Lbl_AnesthType)
                            .addComponent(Lbl_opeCost)
                            .addComponent(Lbl_opeType)))
                    .addComponent(Lbl_opeNurse))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtOpe_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtConvrt_Doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAneths_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_AnethDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblConrt_Doc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblOpe_Date, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtope_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtAssist_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_opeDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_AssistDoctor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPas_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPas_Name)
                .addGap(18, 18, 18)
                .addComponent(txtPas_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblPas_ID)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPas_ID)
                    .addComponent(LblPas_Name)
                    .addComponent(txtPas_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPas_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblOpe_Date)
                    .addComponent(Lbl_opeType)
                    .addComponent(txtOpe_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_opeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_opeCost)
                    .addComponent(LblConrt_Doc)
                    .addComponent(txtConvrt_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_opeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_AnethDoctor)
                    .addComponent(Lbl_AnesthType)
                    .addComponent(txtAneths_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnthes_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_opeNurse)
                            .addComponent(txtope_Nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_opeDoctor)
                            .addComponent(txtope_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_AssistDoctor)
                    .addComponent(Lbl_opeTechnical)
                    .addComponent(txtAssist_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtope_Technical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("صرف مستهلك عمليات أو أدوية بسعر البيع :");

        Tble_ope_Data.setForeground(new java.awt.Color(255, 255, 255));
        Tble_ope_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tble_ope_Data);

        jLabel3.setText("اجمالى منصرف المستهلك أو الأدوية :");

        LblNotce_Doc.setText("ملاحظات الطبيب :");

        txtNotice_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotice_DocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNotice_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(LblNotce_Doc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotal_Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal_Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblNotce_Doc))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(txtNotice_Doc))
                .addContainerGap())
        );

        Tble_Show_dataFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "إسم المريض"
            }
        ));
        Tble_Show_dataFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tble_Show_dataFileFocusGained(evt);
            }
        });
        Tble_Show_dataFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_Show_dataFileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tble_Show_dataFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    
        Frm_insertPasData iData = new Frm_insertPasData();

        try { iData.setisliad(false, "");
        }catch(Exception x){}
        iData.setVisible(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
       
        Frm_insertPasData iData = new Frm_insertPasData();
        try {
            String Pas_id = null;
            if(Pas_id == ""){Pas_id=1+"";}
            iData.setisliad(true, Pas_id);
        }catch(Exception x){}

        iData.setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtNotice_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotice_DocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotice_DocActionPerformed

    private void Tble_Show_dataFileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_Tble_Show_dataFileFocusGained

    private void Tble_Show_dataFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileMouseClicked

        int row = Tble_Show_dataFile.rowAtPoint(evt.getPoint());

        int col = Tble_Show_dataFile.columnAtPoint(evt.getPoint());

        String valueInCell = (String)Tble_Show_dataFile.getValueAt(row, col);

        String id = pasdata.dataTableShow.getvalue(row, pasdata.ID);
        String name = pasdata.dataTableShow.getvalue(row, pasdata.Name);
        System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
        Pas_id = id ; Pas_Name = name ;
         
        pasLoadData(id); 
    }

        
        void pasLoadData(String id){
    try {
        pasdata.LoadFile_id(id);
    } catch (SQLException ex) {
        Logger.getLogger(pnl_ope_Srv.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(pnl_ope_Srv.class.getName()).log(Level.SEVERE, null, ex);
    }
     txtPas_ID.setText(pas_opeSrv.getValue(pas_opeSrv.Pasiont_id));
    txtPas_Name.setText(pas_opeSrv.getValue(pas_opeSrv.PasiontName));
    txtOpe_Date.setText(pas_opeSrv.getValue(pas_opeSrv.Ope_Date));                          
    txt_opeType.setText(pas_opeSrv.getValue(pas_opeSrv.OpeType));
    txtope_Nurse.setText(pas_opeSrv.getValue(pas_opeSrv.OpeNurse));
    txtope_Doctor.setText(pas_opeSrv.getValue(pas_opeSrv.OpeDoctor));
    txt_opeCost.setText(pas_opeSrv.getValue(pas_opeSrv.OpeCost));
    txtConvrt_Doc.setText(pas_opeSrv.getValue(pas_opeSrv.Convert_Doc));
    txtAssist_Doctor.setText(pas_opeSrv.getValue(pas_opeSrv.AssDoctor));
    txtAnthes_Type.setText(pas_opeSrv.getValue(pas_opeSrv.AnsType));
    txtAneths_Doctor.setText(pas_opeSrv.getValue(pas_opeSrv.AnsDoctor));
  
    
    }//GEN-LAST:event_Tble_Show_dataFileMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblConrt_Doc;
    private javax.swing.JLabel LblNotce_Doc;
    private javax.swing.JLabel LblOpe_Date;
    private javax.swing.JLabel LblPas_ID;
    private javax.swing.JLabel LblPas_Name;
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel Lbl_AnesthType;
    private javax.swing.JLabel Lbl_AnethDoctor;
    private javax.swing.JLabel Lbl_AssistDoctor;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JLabel Lbl_opeCost;
    private javax.swing.JLabel Lbl_opeDoctor;
    private javax.swing.JLabel Lbl_opeNurse;
    private javax.swing.JLabel Lbl_opeTechnical;
    private javax.swing.JLabel Lbl_opeType;
    private javax.swing.JTable Tble_Show_dataFile;
    private javax.swing.JTable Tble_ope_Data;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private projict_Class.TxTf txtAneths_Doctor;
    private projict_Class.TxTf txtAnthes_Type;
    private projict_Class.TxTf txtAssist_Doctor;
    private projict_Class.TxTf txtConvrt_Doc;
    private javax.swing.JTextField txtNotice_Doc;
    private projict_Class.TxTf txtOpe_Date;
    private projict_Class.TxTf txtPas_ID;
    private projict_Class.TxTf txtPas_Name;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    private javax.swing.JTextField txtTotal_Revenue;
    private projict_Class.TxTf txt_opeCost;
    private projict_Class.TxTf txt_opeType;
    private projict_Class.TxTf txtope_Doctor;
    private projict_Class.TxTf txtope_Nurse;
    private projict_Class.TxTf txtope_Technical;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Insert() {
insert();    }

    @Override
    public void Update() {
update();    }

    @Override
    public void Delete() {
delete();    }

    @Override
    public void Addnew() {
txtAneths_Doctor.setText("");
txtAnthes_Type.setText("");
txtAssist_Doctor.setText(""); 
    txtConvrt_Doc.setText("");
    txtNotice_Doc.setText("");
    txtOpe_Date.setText("");
    txtPas_ID.setText("");
    txtPas_Name.setText("");
    txtTotal_Revenue.setText("");
    txt_opeCost.setText("");
    txt_opeType.setText("");
    txtope_Doctor.setText("");
    txtope_Nurse.setText("");
    txtope_Technical.setText("");
    
    }
   
}
