/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;


import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Z_connection;
 

/**
 *
 * @author aman
 */
public class pnl_report_pasFile extends javax.swing.JPanel 
{
        Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
AmanPasDatabse_PasdataTable pasdata=new AmanPasDatabse_PasdataTable(z_connection);
AmanPasDatabse_PasdataFile pasFile=new AmanPasDatabse_PasdataFile(z_connection);
     String Pas_id = "1" , Pas_Name  ;
     
public boolean isLoad=true;
   
    public pnl_report_pasFile() {
        initComponents();
        try{
            loadData();
             TxtVent();
            
        }
        catch(Exception e){System.out.println(e);}
    }
    
        void loadData() throws SQLException, ParseException{
    if(isLoad){
    Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview_name(""));
}
    }
        
         void TxtVent(){
  
 txtSearchName_Pas_Data.getDocument().addDocumentListener(new DocumentListener() {
 String s = ""; 
     
     @Override
   
    public void insertUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText();
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
     }
  
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText(); 
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
     s = txtSearchName_Pas_Data.getText();    
  
    }
   
    
});
 
    
 }

        
  void pas_SaarchName(String s) throws SQLException, ParseException{
         try {
             Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
         } catch (Exception ex) {
             System.out.println("error in show "+ ex );
            }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblePasFile = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tble_Show_dataFile = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtPationt_ID = new projict_Class.TxTf();
        jLabel5 = new javax.swing.JLabel();
        txtPasiont_Name = new projict_Class.TxTf();
        jLabel1 = new javax.swing.JLabel();
        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();

        jButton1.setText("طباعة");

        TblePasFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblePasFile);

        Tble_Show_dataFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "إسم المريض"
            }
        ));
        Tble_Show_dataFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tble_Show_dataFileFocusGained(evt);
            }
        });
        Tble_Show_dataFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_Show_dataFileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tble_Show_dataFile);

        jLabel4.setText("رقم المريض :");

        jLabel5.setText("اسم المريض :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("تقارير بيانات المرضى :");

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data))
                .addGap(2, 2, 2))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LblSearch_ID_Pas_Data))
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(203, 203, 203)
                                            .addComponent(jLabel5)
                                            .addGap(82, 82, 82)
                                            .addComponent(txtPationt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtPasiont_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(324, 324, 324)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtPationt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasiont_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed

    private void Tble_Show_dataFileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_Tble_Show_dataFileFocusGained

    private void Tble_Show_dataFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileMouseClicked

        int row = Tble_Show_dataFile.rowAtPoint(evt.getPoint());

        int col = Tble_Show_dataFile.columnAtPoint(evt.getPoint());

        String valueInCell = (String)Tble_Show_dataFile.getValueAt(row, col);

        
 String id = pasdata.dataTableShow.getvalue(row, pasdata.ID);
        String name = pasdata.dataTableShow.getvalue(row, pasdata.Name);
        System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
        Pas_id = id ; Pas_Name = name ;
             txtPationt_ID.setText(id);
txtPasiont_Name.setText(name);

        loadPadData(id);

    }//GEN-LAST:event_Tble_Show_dataFileMouseClicked

    void loadPadData(String id){
        try{
        pasFile.LoadFile(id);
      TblePasFile.setModel(pasFile.showinTable(id));
  
   Pas_id=txtPationt_ID.getText();  
        }catch(Exception e){System.out.println(e);}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JTable TblePasFile;
    private javax.swing.JTable Tble_Show_dataFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private projict_Class.TxTf txtPasiont_Name;
    private projict_Class.TxTf txtPationt_ID;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    // End of variables declaration//GEN-END:variables

}
