/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mysql_data_link.ZeftawyTools.Z_connection;
 

/**
 *
 * @author aman
 */
public class pnl_report_patinotVist extends javax.swing.JPanel 
{
            Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
AmanPasDatabse_Visit_table pasVist=new AmanPasDatabse_Visit_table(z_connection);
    AmanPasDatabse_PasdataTable pasdata=new AmanPasDatabse_PasdataTable(z_connection);
    String Pas_id = "1" , Pas_Name  ;
public boolean isLoad=true;
    String file_id = 1+"";
    public pnl_report_patinotVist() {
        initComponents();
                try
        {
        loadData();
        TxtVent();
        }catch(Exception e){System.out.println(e);}

    }
    
            void loadData() throws SQLException, ParseException{
    if(isLoad){
    Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview_name(""));
}
    }
        
         void TxtVent(){
  
 txtSearchName_Pas_Data.getDocument().addDocumentListener(new DocumentListener() {
 String s = ""; 
     
     @Override
   
    public void insertUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText();
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_report_patinotVist.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_report_patinotVist.class.getName()).log(Level.SEVERE, null, ex);
     }
  
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText(); 
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_report_patinotVist.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_report_patinotVist.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
     s = txtSearchName_Pas_Data.getText();   
    } 
});   
 }       
           void pas_SaarchName(String s) throws SQLException, ParseException{
         try {
            Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
         }catch(Exception ex){}         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        aLable1 = new projict_Class.ALable();
        txt_pasName = new projict_Class.TxTf();
        aLable2 = new projict_Class.ALable();
        txt_pasID = new projict_Class.TxTf();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aCalender1 = new projict_Class.ACalender();
        aCalender2 = new projict_Class.ACalender();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tble_Show_dataFile = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data)))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSearch_ID_Pas_Data)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        aLable1.setText("اسم المريض :");

        aLable2.setText("رقم المريض :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_pasName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aLable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_pasID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aLable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pasName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("من تاريخ :");

        jLabel3.setText("إلى تاريخ :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(aCalender2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(aCalender1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(aCalender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aCalender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Tble_Show_dataFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "إسم المريض"
            }
        ));
        Tble_Show_dataFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tble_Show_dataFileFocusGained(evt);
            }
        });
        Tble_Show_dataFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_Show_dataFileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tble_Show_dataFile);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("تقرير زيارات المرضى :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed

    private void Tble_Show_dataFileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_Tble_Show_dataFileFocusGained

    private void Tble_Show_dataFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileMouseClicked

        int row = Tble_Show_dataFile.rowAtPoint(evt.getPoint());

        int col = Tble_Show_dataFile.columnAtPoint(evt.getPoint());

        String valueInCell = (String)Tble_Show_dataFile.getValueAt(row, col);

       String id = pasdata.dataTableShow.getvalue(row, pasdata.ID);
       String name = pasdata.dataTableShow.getvalue(row, pasdata.Name);
        System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
        Pas_id = id ; Pas_Name = name ;
                     txt_pasID.setText(id);
txt_pasName.setText(name);


        try {
            pasLoadData(id);
        } catch (SQLException ex) {
            Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_report_pasFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

        void pasLoadData(String id) throws SQLException, ParseException{
   pasVist.LoadFile_id(id);
  jTable1.setModel( pasVist.showInmainTable(id));
Pas_id=txt_pasID.getText();
            
        

    }//GEN-LAST:event_Tble_Show_dataFileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JTable Tble_Show_dataFile;
    private projict_Class.ACalender aCalender1;
    private projict_Class.ACalender aCalender2;
    private projict_Class.ALable aLable1;
    private projict_Class.ALable aLable2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    private projict_Class.TxTf txt_pasID;
    private projict_Class.TxTf txt_pasName;
    // End of variables declaration//GEN-END:variables

 }
