/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projict_Class;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.Icon; 
import javax.swing.border.Border;
       

/**
 *
 * @author New
 */
public class A_imgabutton extends javax.swing.JPanel {
String Text= "معاذ الزفتاوي";
    Color defBackground  = Color.gray;
Color MousemoveBackground = Color.darkGray;
     Icon imge ;
     Font  mefont ; Color Froground;

    public Font getmeFont() {
        return mefont;
    }

    public void setmeFont(Font mefont) {
        this.mefont = mefont;
      setFont(mefont);
      jLabel1.setFont(mefont);
    }

    public Color getFroground() {
        return Froground;
    }

    public void setFroground(Color Froground) {
        this.Froground = Froground;
        jLabel1.setForeground(Froground);
    }

    public Icon getImge() {
        return imge;
    }

    public void setImge(Icon imge) {
      ImageIcon imi= (ImageIcon) imge;
      a_imgebox2.setImage(imi.getImage());
        this.imge = imge;
    }
     
    
    public String getText() {
        return Text;
    }

    public void setText(String Text) {
      jLabel1.setText(Text);
        this.Text = Text;
    }

    public Color getDefBackground() {
      
        return defBackground;
    }

    public void setDefBackground(Color defBackground) {
        
        this.defBackground = defBackground;
        setBackground(defBackground);
       
    }

    public Color getMousemoveBackground() {
        return MousemoveBackground;
    }

    public void setMousemoveBackground(Color MousemoveBackground) {
        this.MousemoveBackground = MousemoveBackground;
    }


     
    public A_imgabutton() {
        initComponents();
        setBackground(defBackground);
        jLabel1.setText(Text);
        jLabel1.setFont(mefont);
        jLabel1.setForeground(getForeground());
         jLabel1.setForeground(Froground);
        if (imge!= null){
             ImageIcon imi= (ImageIcon) imge;
      a_imgebox2.setImage(imi.getImage());
      
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a_imgebox2 = new projict_Class.A_imgebox();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        a_imgebox2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout a_imgebox2Layout = new javax.swing.GroupLayout(a_imgebox2);
        a_imgebox2.setLayout(a_imgebox2Layout);
        a_imgebox2Layout.setHorizontalGroup(
            a_imgebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        a_imgebox2Layout.setVerticalGroup(
            a_imgebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(a_imgebox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(a_imgebox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

        setBackground(MousemoveBackground);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(defBackground);
          Border b ;
        BorderFactory.createRaisedSoftBevelBorder();
        setBorder(BorderFactory.createRaisedSoftBevelBorder());
   
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Border b ;
        BorderFactory.createEmptyBorder();
        setBorder(BorderFactory.createEmptyBorder());
       evt.getModifiers();
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projict_Class.A_imgebox a_imgebox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
