


import mysql_data_link.Passoin.*;
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mysql_data_link.ZeftawyTools.Z_connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class Frm_pasiont_data extends javax.swing.JFrame {
     public String file_id="1";

    AmanPasDatabse_PasdataTable pasdata;
 public boolean isLoad=true;
 String Pas_id , Pas_Name  ;



    public Frm_pasiont_data() {
        initComponents();
        try{
        LoadFile();
        TxtVent();
            setLocationRelativeTo(null);
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        Tble_pas_dataShow.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }
    
    void LoadFile() throws SQLException, ParseException{
    if(isLoad){
            Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
        pasdata=new AmanPasDatabse_PasdataTable(z_connection); 
   Tble_pas_dataShow.setModel(pasdata.LoadFile_id_showTableview_name_dataShow(""));
    
    }
    }
    
             void TxtVent(){
  
 txtSearchName_Pas_Data.getDocument().addDocumentListener(new DocumentListener() {
 String s = ""; 
     
     @Override
   
    public void insertUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText();
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
  
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText(); 
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
     s = txtSearchName_Pas_Data.getText();    
  
    }
   
    
});
 
    
 }
 
 void pas_SaarchName(String s) throws SQLException, ParseException{
Tble_pas_dataShow.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
 
 }   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_First_Vist1 = new Pnl_First_Vist();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tble_pas_dataShow = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Tble_pas_dataShow.setBackground(new java.awt.Color(253, 253, 212));
        Tble_pas_dataShow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tble_pas_dataShow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tble_pas_dataShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "رقم المريض", "إسم المريض"
            }
        ));
        Tble_pas_dataShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_pas_dataShowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tble_pas_dataShow);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnUpdate.setText("حفظ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("حذف ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("مريض جديد");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data))
                .addGap(33, 33, 33))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSearch_ID_Pas_Data)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_First_Vist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_First_Vist1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tble_pas_dataShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_pas_dataShowMouseClicked
       
        int Row=Tble_pas_dataShow.rowAtPoint(evt.getPoint());
      int column=Tble_pas_dataShow.columnAtPoint(evt.getPoint());
      
     String ValueinCell=(String)Tble_pas_dataShow.getValueAt(Row, column);
    id=pasdata.dataTableShow.getvalue(Row,pasdata.ID);
  String Name=pasdata.dataTableShow.getvalue(Row,pasdata.Name);
        System.out.println("Row"+Row+"Column"+column+"Value in cell"+
                ValueinCell+"id"+id);
  Pas_id=id; Pas_Name=Name;
   try{
       pasLoadData(id);
   }       catch (SQLException ex) {    
               Logger.getLogger(Frm_pasiont_data.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ParseException ex) {
               Logger.getLogger(Frm_pasiont_data.class.getName()).log(Level.SEVERE, null, ex);
           }    
   // TODO add your handling code here:    
   // TODO add your handling code here:
    }//GEN-LAST:event_Tble_pas_dataShowMouseClicked
boolean isaddnew;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
pnl_First_Vist1.Addnew(); 
isaddnew = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
if (isaddnew){
    pnl_First_Vist1.Insert();
}else{
    pnl_First_Vist1.Update();
    try {
        LoadFile();
    } catch (SQLException ex) {
        Logger.getLogger(Frm_pasiont_data.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(Frm_pasiont_data.class.getName()).log(Level.SEVERE, null, ex);
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
pnl_First_Vist1.Delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed
 String id;
    
    void pasLoadData(String id) throws SQLException, ParseException{
pnl_First_Vist1.isload = true;
pnl_First_Vist1.Pas_id= id;
pnl_First_Vist1.loadData();



}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_pasiont_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_pasiont_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_pasiont_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_pasiont_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_pasiont_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JTable Tble_pas_dataShow;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private Pnl_First_Vist pnl_First_Vist1;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    // End of variables declaration//GEN-END:variables
}
