


import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import mysql_data_link.Passoin.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Z_connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class PasFile_EnrerData extends javax.swing.JPanel {
Frm_Medecine frmm = new Frm_Medecine();
Frm_treatment frmTreat=new Frm_treatment();
AmanPasDatabse_PasdataTable pasData;
AmanPasDatabse_Visit_table pasVist;
String Pas_id="1" ; String Pas_name ; 
        public PasFile_EnrerData() {
        initComponents();
        try{
 Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
            pasVist = new AmanPasDatabse_Visit_table(z_connection);
            
        loadData();
        }catch(Exception e){System.out.println(e);}
    
    }
        
    void loadData() throws SQLException, ParseException{
pasVist.setconrotl(txtID_otherData, txtName_otherData, txtExamType, txtExamValue, txtDoctor, txtTime, txtDate);
pasVist.LoadSelected_pas(Pas_id);


    }
        
    public  void movefirst(){pasData.movefirst();} 
public void movepre(){pasData.movepre();}
public  void movenext(){pasData.movenext();} 
public  void movelast(){pasData.movelast();}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Other_Data = new javax.swing.JPanel();
        Lbl_OtherData = new javax.swing.JLabel();
        LblSrv_Type_otherData = new javax.swing.JLabel();
        LblExam_Type_otherData = new javax.swing.JLabel();
        LblTreat_Doc_otherData = new javax.swing.JLabel();
        LblDate_Vist_otherData = new javax.swing.JLabel();
        LblTimeVist_otherData = new javax.swing.JLabel();
        LblLst_dateVist_otherData = new javax.swing.JLabel();
        LblTreat_Requst_otherData = new javax.swing.JLabel();
        txtDetails = new projict_Class.TxTf();
        LblDetails_otherData = new javax.swing.JLabel();
        LblName_otherData = new javax.swing.JLabel();
        txtName_otherData = new projict_Class.TxTf();
        LblID_otherData = new javax.swing.JLabel();
        txtID_otherData = new projict_Class.TxTf();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_medecion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tble_Require = new javax.swing.JTable();
        btnDelete1 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        txtExamType = new projict_Class.TxTf();
        txtExamValue = new projict_Class.TxTf();
        txtDoctor = new projict_Class.TxTf();
        txtTime = new projict_Class.TxTf();
        txtDate = new projict_Class.TxTf();
        LblDetails_otherData1 = new javax.swing.JLabel();
        Cln_NextVist = new projict_Class.ACalender();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        pnl_Other_Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lbl_OtherData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lbl_OtherData.setText("بيانات أخرى :");

        LblSrv_Type_otherData.setText("نوع الكشف :");

        LblExam_Type_otherData.setText("قيمة الكشف :");

        LblTreat_Doc_otherData.setText("الطبيب المعالج :");

        LblDate_Vist_otherData.setText("تاريخ الزيارة :");

        LblTimeVist_otherData.setText("وقت الزيارة :");

        LblLst_dateVist_otherData.setText("تاريخ الزيارة القادمة :");

        LblTreat_Requst_otherData.setText("الحالة");

        LblDetails_otherData.setText("تقرير الحالة");

        LblName_otherData.setText("الإســـــــــم :");

        txtName_otherData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_otherDataActionPerformed(evt);
            }
        });

        LblID_otherData.setText("رقم المريض :");

        Table_medecion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الدواء", "الاستخدام"
            }
        ));
        Table_medecion.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(Table_medecion);

        Tble_Require.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "طلب كشف", "الجهه"
            }
        ));
        jScrollPane2.setViewportView(Tble_Require);

        btnDelete1.setText("اضافة");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnDelete2.setText("اضافة");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });

        LblDetails_otherData1.setText("الادوية :");

        javax.swing.GroupLayout pnl_Other_DataLayout = new javax.swing.GroupLayout(pnl_Other_Data);
        pnl_Other_Data.setLayout(pnl_Other_DataLayout);
        pnl_Other_DataLayout.setHorizontalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                .addComponent(Lbl_OtherData)
                                .addGap(4, 4, 4))
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Cln_NextVist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblLst_dateVist_otherData)
                                    .addComponent(LblDate_Vist_otherData))
                                .addGap(38, 38, 38)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblTimeVist_otherData))
                                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblTreat_Doc_otherData)))
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(txtExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(LblExam_Type_otherData))
                                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtExamType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblSrv_Type_otherData)))))
                        .addGap(13, 13, 13))
                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDelete1)
                                    .addComponent(btnDelete2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))))
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(LblDetails_otherData))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LblDetails_otherData1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(LblTreat_Requst_otherData)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblName_otherData)
                .addGap(37, 37, 37)
                .addComponent(txtID_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblID_otherData)
                .addGap(72, 72, 72))
        );
        pnl_Other_DataLayout.setVerticalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Lbl_OtherData)
                .addGap(13, 13, 13)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblID_otherData)
                                .addComponent(txtID_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblName_otherData)
                                .addComponent(txtName_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblTreat_Doc_otherData)
                                .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtExamType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblSrv_Type_otherData)))
                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblDate_Vist_otherData, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTimeVist_otherData)
                    .addComponent(LblExam_Type_otherData)
                    .addComponent(LblLst_dateVist_otherData)
                    .addComponent(txtExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cln_NextVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete2)
                        .addGap(31, 31, 31))
                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(LblDetails_otherData1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addComponent(LblDetails_otherData)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addComponent(btnDelete1)
                        .addGap(63, 63, 63)))
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTreat_Requst_otherData)
                    .addComponent(txtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnUpdate.setText("حفظ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Other_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Other_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
     AmanPasDatabse_PasdataFile pasDatabse=new AmanPasDatabse_PasdataFile(z_connection);
        OtherMethods M=new OtherMethods();
    try { 
        pasDatabse.PationtFileData(txtID_otherData.getValue() ,  txtName_otherData.getValue(), txtExamType.getValue(),
               txtExamValue.getValue() ,   txtDoctor.getValue(), txtTime.getValue(),
                txtDate.getValue(), Cln_NextVist.getValue(),
                midecalStr,txtDetails.getValue() ,reqStr);
    } catch (SQLException ex) {
        Logger.getLogger(PasFile_EnrerData.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(PasFile_EnrerData.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(PasFile_EnrerData.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnUpdateActionPerformed
void addMed(){
Table_medecion.getModel().addTableModelListener(new TableModelListener() {
    @Override
    public void tableChanged(TableModelEvent e) {
 if (e.getType() == TableModelEvent.INSERT){
     System.out.println("dd");
 }
    }
} );

 
}
    private void txtName_otherDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_otherDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_otherDataActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
          code = 2 ; 
        frmTreat.setVisible(true);

    }//GEN-LAST:event_btnDelete1ActionPerformed
int code ;
String midecalStr= ""; 
String reqStr= ""; 
    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
  code = 1 ; 
        frmm.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete2ActionPerformed

    
  public  void AddMedecal(){
       code = 0 ;
if (!frmm.isVisible() && frmm.isGetData()){  
  DefaultTableModel model = (DefaultTableModel) Table_medecion.getModel();
 midecalStr= midecalStr + " / " + frmm.medecion+ "-->"+frmm.Treatment ;
  model.addRow(new Object[]{frmm.medecion , frmm.Treatment });
  frmm.dispose();}
      System.out.println(" medecat " + midecalStr);
  }
  
    public  void AddReq(){
     code = 0 ;
     if(!frmTreat.isVisible() && frmTreat.isGetData()){
  DefaultTableModel model = (DefaultTableModel) Tble_Require.getModel();
 
  reqStr= reqStr + " / " + frmTreat.Requre+ "-->"+frmTreat.direc ;
 
  model.addRow(new Object[]{frmTreat.Requre , frmTreat.direc });
  frmTreat.dispose();
     }
  }

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

   
 
        
    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projict_Class.ACalender Cln_NextVist;
    private javax.swing.JLabel LblDate_Vist_otherData;
    private javax.swing.JLabel LblDetails_otherData;
    private javax.swing.JLabel LblDetails_otherData1;
    private javax.swing.JLabel LblExam_Type_otherData;
    private javax.swing.JLabel LblID_otherData;
    private javax.swing.JLabel LblLst_dateVist_otherData;
    private javax.swing.JLabel LblName_otherData;
    private javax.swing.JLabel LblSrv_Type_otherData;
    private javax.swing.JLabel LblTimeVist_otherData;
    private javax.swing.JLabel LblTreat_Doc_otherData;
    private javax.swing.JLabel LblTreat_Requst_otherData;
    private javax.swing.JLabel Lbl_OtherData;
    private javax.swing.JTable Table_medecion;
    private javax.swing.JTable Tble_Require;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_Other_Data;
    private projict_Class.TxTf txtDate;
    private projict_Class.TxTf txtDetails;
    private projict_Class.TxTf txtDoctor;
    private projict_Class.TxTf txtExamType;
    private projict_Class.TxTf txtExamValue;
    private projict_Class.TxTf txtID_otherData;
    private projict_Class.TxTf txtName_otherData;
    private projict_Class.TxTf txtTime;
    // End of variables declaration//GEN-END:variables
}
