


import mysql_data_link.Passoin.*;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Toast;
import mysql_data_link.ZeftawyTools.Z_connection;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class Pnl_First_Vist extends javax.swing.JPanel  
implements  IDataEntery {

public boolean isload= false;
public  String Pas_id="1";
   Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
       AmanPasDatabse_PasdataTable pasDatabse =new AmanPasDatabse_PasdataTable(z_connection);
      
    public Pnl_First_Vist()  {
   try{
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        ClnDateBirth_FrstVist.setFormats("dd/MMM/yyyy");
       loadData();
   showCombo();
   }
       catch(Exception e){
           System.out.println(e);
       }
    }
public void loadData() throws SQLException, ParseException{

if (isload){
        
       pasDatabse.LoadFile_id(Pas_id);
      txtName_Pas_Data.setText(pasDatabse.getValue(pasDatabse.Name));
    OtherMethods o = new OtherMethods();
    txt_pasID.setText(pasDatabse.getValue(pasDatabse.ID));
      ClnDateBirth_FrstVist.setDate(
           o.GetStringVal(pasDatabse.getValue(pasDatabse.DateBirth)));
        CmbGender_FrstVist.setSelectedItem(pasDatabse.getValue(pasDatabse.Gender));
        txtAge_Pas_Data.setText(pasDatabse.getValue(pasDatabse.Age));
    CmbJob_FistVist.setSelectedItem(pasDatabse.getValue(pasDatabse.Job));
    txtAddress_Pas_Data.setText(pasDatabse.getValue(pasDatabse.Address));
    txtMob_Pas_Data.setText(pasDatabse.getValue(pasDatabse.Mob));
    CmbGovFrstVist.setSelectedItem(pasDatabse.getValue(pasDatabse.Gov));
    CmbMarital_Status_FrstVist.setSelectedItem(pasDatabse.getValue(pasDatabse.Status));
    txtHome_Phone_Pas_Data.setText(pasDatabse.getValue(pasDatabse.HomePhone));
    txtHeight_Pas_Status.setText(pasDatabse.getValue(pasDatabse.Height));
    txtWeight_Pas_Status.setText(pasDatabse.getValue(pasDatabse.Weight));
    txtSugar_Pas_Status.setText(pasDatabse.getValue(pasDatabse.Suger));
    txthymoglobine_pasData.setText(pasDatabse.getValue(pasDatabse.hymoglobin));
    txtBlood_pasData.setText(pasDatabse.getValue(pasDatabse.Blood));
 String Rsee , LSee, see;
 see = pasDatabse.getValue(pasDatabse.See);
String sees[] = see.split(" / ");
Rsee = sees[0].substring(2);
LSee = sees[1].substring(2);
txtRight_Eye_Pas_Status.setText(Rsee);
txtLeft_Eye_Pas_Status.setText(LSee);



}else{}
}

void showCombo(){
 try{
 pasDatabse.ComboFill(CmbJob_FistVist, pasDatabse.Job);
 pasDatabse.ComboFill(CmbGovFrstVist, pasDatabse.Gov);
 
 txt_pasID.setText(pasDatabse.getNom(Pas_id)+"");

 }
catch(Exception e){System.out.println(e);}
}  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPas_FrstData = new javax.swing.JPanel();
        pnl_Main_Data = new javax.swing.JPanel();
        LblSet_Data = new javax.swing.JLabel();
        LblName_Pas_Data = new javax.swing.JLabel();
        LblID_Pas_Data = new javax.swing.JLabel();
        LblDateBirth_Pas_Data = new javax.swing.JLabel();
        LblGender_Pas_Data = new javax.swing.JLabel();
        LblJob_Pas_Data = new javax.swing.JLabel();
        LblAddress_Pas_Data = new javax.swing.JLabel();
        LblGov_Pas_Data = new javax.swing.JLabel();
        LblMarital_Status_Pas_Data = new javax.swing.JLabel();
        LblMob_Pas_Data = new javax.swing.JLabel();
        LblHome_Phone_Pas_Data = new javax.swing.JLabel();
        LblAge_Pas_Data = new javax.swing.JLabel();
        ClnDateBirth_FrstVist = new org.jdesktop.swingx.JXDatePicker();
        CmbGender_FrstVist = new javax.swing.JComboBox<>();
        CmbJob_FistVist = new javax.swing.JComboBox<>();
        CmbGovFrstVist = new javax.swing.JComboBox<>();
        CmbMarital_Status_FrstVist = new javax.swing.JComboBox<>();
        txt_pasID = new projict_Class.TxTf();
        txtName_Pas_Data = new projict_Class.TxTf();
        txtAge_Pas_Data = new projict_Class.TxTf();
        txtAddress_Pas_Data = new projict_Class.TxTf();
        txtMob_Pas_Data = new projict_Class.TxTf();
        txtHome_Phone_Pas_Data = new projict_Class.TxTf();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlPas_Status = new javax.swing.JPanel();
        LblPas_Status = new javax.swing.JLabel();
        LblHeight_Pas_Status = new javax.swing.JLabel();
        LblWeight_Pas_Status = new javax.swing.JLabel();
        LblSugar_Pas_Status = new javax.swing.JLabel();
        LblBlood_Pas_Status = new javax.swing.JLabel();
        LblHymoglopin_Pas_Status = new javax.swing.JLabel();
        LblRight_Eye_Pas_Status = new javax.swing.JLabel();
        LblLeft_Eye_Pas_Status = new javax.swing.JLabel();
        txtHeight_Pas_Status = new projict_Class.TxTf();
        txtWeight_Pas_Status = new projict_Class.TxTf();
        txtSugar_Pas_Status = new projict_Class.TxTf();
        txtBlood_pasData = new projict_Class.TxTf();
        txthymoglobine_pasData = new projict_Class.TxTf();
        txtRight_Eye_Pas_Status = new projict_Class.TxTf();
        txtLeft_Eye_Pas_Status = new projict_Class.TxTf();

        pnlPas_FrstData.setBackground(new java.awt.Color(204, 204, 204));

        pnl_Main_Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblSet_Data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblSet_Data.setText("البيانات الأساسية :");

        LblName_Pas_Data.setText("الاسم :");

        LblID_Pas_Data.setText("رقم المريض :");

        LblDateBirth_Pas_Data.setText("تاريخ الميلاد :");

        LblGender_Pas_Data.setText("الجنس :");

        LblJob_Pas_Data.setText("الوظيفة :");

        LblAddress_Pas_Data.setText("العنوان :");

        LblGov_Pas_Data.setText("المحافظة :");

        LblMarital_Status_Pas_Data.setText("الحالة الاجتماعية :");

        LblMob_Pas_Data.setText("موبايل :");

        LblHome_Phone_Pas_Data.setText("ت المنزل :");

        LblAge_Pas_Data.setText("السن:");

        ClnDateBirth_FrstVist.setDoubleBuffered(true);
        ClnDateBirth_FrstVist.setNextFocusableComponent(CmbJob_FistVist);
        ClnDateBirth_FrstVist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClnDateBirth_FrstVistActionPerformed(evt);
            }
        });

        CmbGender_FrstVist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ذكر", "أنثى", " ", " " }));
        CmbGender_FrstVist.setNextFocusableComponent(txtAddress_Pas_Data);

        CmbJob_FistVist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));
        CmbJob_FistVist.setNextFocusableComponent(CmbGovFrstVist);

        CmbGovFrstVist.setNextFocusableComponent(CmbGender_FrstVist);

        CmbMarital_Status_FrstVist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "متزوج", "أعزب", "أرمل", "مطلق" }));
        CmbMarital_Status_FrstVist.setNextFocusableComponent(txtAge_Pas_Data);

        txt_pasID.setEnabled(false);
        txt_pasID.setNextFocusableComponent(txtName_Pas_Data);

        txtName_Pas_Data.setNextFocusableComponent(ClnDateBirth_FrstVist);

        txtAge_Pas_Data.setNextFocusableComponent(txtMob_Pas_Data);

        txtAddress_Pas_Data.setNextFocusableComponent(LblMarital_Status_Pas_Data);

        txtMob_Pas_Data.setNextFocusableComponent(LblHome_Phone_Pas_Data);

        txtHome_Phone_Pas_Data.setNextFocusableComponent(txtHeight_Pas_Status);

        jButton1.setText("....");
        jButton1.setToolTipText("ادخال جديد");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("....");
        jButton2.setToolTipText("ادخال جديد");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Main_DataLayout = new javax.swing.GroupLayout(pnl_Main_Data);
        pnl_Main_Data.setLayout(pnl_Main_DataLayout);
        pnl_Main_DataLayout.setHorizontalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmbMarital_Status_FrstVist, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbGovFrstVist, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblMarital_Status_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblGov_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblHome_Phone_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CmbJob_FistVist, 0, 139, Short.MAX_VALUE)
                            .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblAddress_Pas_Data)
                            .addComponent(LblJob_Pas_Data)
                            .addComponent(LblMob_Pas_Data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClnDateBirth_FrstVist, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(CmbGender_FrstVist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblGender_Pas_Data)
                            .addComponent(LblDateBirth_Pas_Data)
                            .addComponent(LblAge_Pas_Data))
                        .addGap(8, 8, 8))
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(txt_pasID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblID_Pas_Data)
                            .addComponent(LblName_Pas_Data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblSet_Data)))
                .addContainerGap())
        );
        pnl_Main_DataLayout.setVerticalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addComponent(LblSet_Data)
                        .addGap(40, 40, 40))
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblID_Pas_Data)
                            .addComponent(txt_pasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(LblName_Pas_Data))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblJob_Pas_Data)
                        .addComponent(LblGov_Pas_Data)
                        .addComponent(LblDateBirth_Pas_Data)
                        .addComponent(CmbJob_FistVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CmbGovFrstVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(ClnDateBirth_FrstVist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblGender_Pas_Data)
                        .addComponent(CmbGender_FrstVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblMarital_Status_Pas_Data)
                        .addComponent(LblAddress_Pas_Data)
                        .addComponent(CmbMarital_Status_FrstVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblHome_Phone_Pas_Data)
                        .addComponent(LblAge_Pas_Data)
                        .addComponent(LblMob_Pas_Data)
                        .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlPas_Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblPas_Status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblPas_Status.setText("حالة المريض :");

        LblHeight_Pas_Status.setText("الطول :");

        LblWeight_Pas_Status.setText("الوزن :");

        LblSugar_Pas_Status.setText("السكر :");

        LblBlood_Pas_Status.setText("فصيلة الدم :");

        LblHymoglopin_Pas_Status.setText("الهيموجلبين :");

        LblRight_Eye_Pas_Status.setText("العين اليمنى :");

        LblLeft_Eye_Pas_Status.setText("العين اليسرى :");

        txtHeight_Pas_Status.setNextFocusableComponent(txtWeight_Pas_Status);

        txtWeight_Pas_Status.setNextFocusableComponent(txtSugar_Pas_Status);

        txtSugar_Pas_Status.setNextFocusableComponent(txtBlood_pasData);

        txtBlood_pasData.setNextFocusableComponent(txthymoglobine_pasData);

        txthymoglobine_pasData.setNextFocusableComponent(txtRight_Eye_Pas_Status);

        txtRight_Eye_Pas_Status.setNextFocusableComponent(txtLeft_Eye_Pas_Status);

        txtLeft_Eye_Pas_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeft_Eye_Pas_StatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPas_StatusLayout = new javax.swing.GroupLayout(pnlPas_Status);
        pnlPas_Status.setLayout(pnlPas_StatusLayout);
        pnlPas_StatusLayout.setHorizontalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(txtBlood_pasData, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBlood_Pas_Status)
                .addGap(13, 13, 13)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                        .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(LblSugar_Pas_Status))
                    .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                        .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblLeft_Eye_Pas_Status)))
                .addGap(18, 18, 18)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblRight_Eye_Pas_Status, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblWeight_Pas_Status, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthymoglobine_pasData, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHymoglopin_Pas_Status, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblHeight_Pas_Status, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPas_Status))
        );
        pnlPas_StatusLayout.setVerticalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblPas_Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblHeight_Pas_Status)
                        .addComponent(LblWeight_Pas_Status)
                        .addComponent(LblSugar_Pas_Status)
                        .addComponent(LblBlood_Pas_Status)
                        .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBlood_pasData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblHymoglopin_Pas_Status)
                        .addComponent(LblRight_Eye_Pas_Status)
                        .addComponent(LblLeft_Eye_Pas_Status)
                        .addComponent(txthymoglobine_pasData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pnlPas_FrstDataLayout = new javax.swing.GroupLayout(pnlPas_FrstData);
        pnlPas_FrstData.setLayout(pnlPas_FrstDataLayout);
        pnlPas_FrstDataLayout.setHorizontalGroup(
            pnlPas_FrstDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_FrstDataLayout.createSequentialGroup()
                .addGroup(pnlPas_FrstDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Main_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPas_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPas_FrstDataLayout.setVerticalGroup(
            pnlPas_FrstDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_FrstDataLayout.createSequentialGroup()
                .addComponent(pnl_Main_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPas_FrstData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPas_FrstData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
int age ;
    private void ClnDateBirth_FrstVistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClnDateBirth_FrstVistActionPerformed
age = new OtherMethods().getage(ClnDateBirth_FrstVist.getDate());
      
txtAge_Pas_Data.setText(age + "");
// TODO add your handling code here:
    }//GEN-LAST:event_ClnDateBirth_FrstVistActionPerformed

    private void txtLeft_Eye_Pas_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeft_Eye_Pas_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeft_Eye_Pas_StatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String t=JOptionPane.showInputDialog("ادخال جديد");
        CmbGovFrstVist.addItem(t);
CmbGovFrstVist.getSelectedItem();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String t=JOptionPane.showInputDialog("ادخال جديد");
        CmbGovFrstVist.addItem(t);
CmbGovFrstVist.getSelectedItem();
    }//GEN-LAST:event_jButton2ActionPerformed

void isert(){
 try{pasDatabse.PasiontmainData(
                txtName_Pas_Data.getText(),
                txtAge_Pas_Data.getText(),
                CmbMarital_Status_FrstVist.getSelectedItem()+"",
            CmbGender_FrstVist.getSelectedItem()+"",
           
         new SimpleDateFormat("yyyy-MM-dd").format(   ClnDateBirth_FrstVist.getDate()),
            
            CmbJob_FistVist.getSelectedItem()+"",
            txtAddress_Pas_Data.getText(),
            CmbGovFrstVist.getSelectedItem()+"",
            txtMob_Pas_Data.getText(),
            txtHome_Phone_Pas_Data.getText(),
            txtWeight_Pas_Status.getText(),
            txtHeight_Pas_Status.getText(),
            txtSugar_Pas_Status.getText(),
            "R :"+txtRight_Eye_Pas_Status.getText() +
                       " / L :"+txtLeft_Eye_Pas_Status.getText(),
                        txtBlood_pasData.getText(),
            txthymoglobine_pasData.getText());
   Toast t = new Toast();
        t.Showtoast("تم حفظ جديد");     
 }catch(Exception ex){
            System.out.println("Error insert " + ex);

}
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker ClnDateBirth_FrstVist;
    private javax.swing.JComboBox<String> CmbGender_FrstVist;
    private javax.swing.JComboBox<String> CmbGovFrstVist;
    private javax.swing.JComboBox<String> CmbJob_FistVist;
    private javax.swing.JComboBox<String> CmbMarital_Status_FrstVist;
    private javax.swing.JLabel LblAddress_Pas_Data;
    private javax.swing.JLabel LblAge_Pas_Data;
    private javax.swing.JLabel LblBlood_Pas_Status;
    private javax.swing.JLabel LblDateBirth_Pas_Data;
    private javax.swing.JLabel LblGender_Pas_Data;
    private javax.swing.JLabel LblGov_Pas_Data;
    private javax.swing.JLabel LblHeight_Pas_Status;
    private javax.swing.JLabel LblHome_Phone_Pas_Data;
    private javax.swing.JLabel LblHymoglopin_Pas_Status;
    private javax.swing.JLabel LblID_Pas_Data;
    private javax.swing.JLabel LblJob_Pas_Data;
    private javax.swing.JLabel LblLeft_Eye_Pas_Status;
    private javax.swing.JLabel LblMarital_Status_Pas_Data;
    private javax.swing.JLabel LblMob_Pas_Data;
    private javax.swing.JLabel LblName_Pas_Data;
    private javax.swing.JLabel LblPas_Status;
    private javax.swing.JLabel LblRight_Eye_Pas_Status;
    private javax.swing.JLabel LblSet_Data;
    private javax.swing.JLabel LblSugar_Pas_Status;
    private javax.swing.JLabel LblWeight_Pas_Status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel pnlPas_FrstData;
    private javax.swing.JPanel pnlPas_Status;
    private javax.swing.JPanel pnl_Main_Data;
    private projict_Class.TxTf txtAddress_Pas_Data;
    private projict_Class.TxTf txtAge_Pas_Data;
    private projict_Class.TxTf txtBlood_pasData;
    private projict_Class.TxTf txtHeight_Pas_Status;
    private projict_Class.TxTf txtHome_Phone_Pas_Data;
    private projict_Class.TxTf txtLeft_Eye_Pas_Status;
    private projict_Class.TxTf txtMob_Pas_Data;
    private projict_Class.TxTf txtName_Pas_Data;
    private projict_Class.TxTf txtRight_Eye_Pas_Status;
    private projict_Class.TxTf txtSugar_Pas_Status;
    private projict_Class.TxTf txtWeight_Pas_Status;
    private projict_Class.TxTf txt_pasID;
    private projict_Class.TxTf txthymoglobine_pasData;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Insert() {
 isert();
      
 
    }

    @Override
    public void Update() {
      
      OtherMethods o = new OtherMethods();
      
       
       try{pasDatabse.PasiontmainDataEdite_id(
                 txt_pasID.getText(),
               txtName_Pas_Data.getText(),
               txtAge_Pas_Data.getText(),
               CmbMarital_Status_FrstVist.getSelectedItem()+"",
               CmbGender_FrstVist.getSelectedItem()+"",
             o.ChangeFrmat( ClnDateBirth_FrstVist.getDate()), 
               CmbJob_FistVist.getSelectedItem()+"",
               txtAddress_Pas_Data.getText(),
               CmbGovFrstVist.getSelectedItem()+"",
               txtMob_Pas_Data.getText(),
               txtHome_Phone_Pas_Data.getText(),
               txtWeight_Pas_Status.getText(),
               txtHeight_Pas_Status.getText(),
               txtSugar_Pas_Status.getText(),
               "R :"+txtRight_Eye_Pas_Status.getText() +
                       " / L :"+txtLeft_Eye_Pas_Status.getText(),
                txtBlood_pasData.getText(),    
                txthymoglobine_pasData.getText()            );
       }
       catch(Exception ex){
           System.out.println("Error"+ex);
       }
       
    }

    @Override
    public void Delete() {
         try{pasDatabse.deletfile_id(Pas_id);   
     }
     catch(Exception ex){
         System.out.println("Error"+ex);
     }
        
    

}

    @Override
    public void Addnew() {
   
      txtName_Pas_Data.setText("");
    OtherMethods o = new OtherMethods();
    txt_pasID.setText("");
 
        txtAge_Pas_Data.setText("");
     txtAddress_Pas_Data.setText("");
    txtMob_Pas_Data.setText("");
   txtHome_Phone_Pas_Data.setText("");
    txtHeight_Pas_Status.setText("");
    txtWeight_Pas_Status.setText("");
    txtSugar_Pas_Status.setText("");
    txthymoglobine_pasData.setText("");
    txtBlood_pasData.setText("");
 txtRight_Eye_Pas_Status.setText("");
txtLeft_Eye_Pas_Status.setText("");

           }
}
