


import mysql_data_link.Passoin.*;
import mysql_data_link.Doctor.AmanDoctorDatabse_doctorData;
import mysql_data_link.Doctor.AmanDatabse_doctorService;
import com.sun.javafx.font.FontConstants;
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Z_connection;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import mysql_data_link.Doctor.AmanDatabse_doctorService;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class pnl_Pas_Data extends javax.swing.JPanel {
     
    public String file_id="1";
    public boolean isLoad=true;
  boolean  loaded = false  ; 
 AmanPasDatabse_PasdataTable pasdata;
 AmanPasDatabse_PasdataFile pasFile;
 AmanPasDatabse_Visit_table VistTable ;
 AmanDatabse_doctorService doctorService;
 Aman_finish_pasRevenue pasReenue; 
 String Pas_id = 1+"" , Pas_Name  ;
    public pnl_Pas_Data()   {
        loaded = false ; 
        initComponents();
        try {
              loadFile(); 
  TxtVent();
         jTabbedPane1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

loaded = true ; 
        } catch (Exception e) {
        }
 
  Tapchange ();
    }
 public void loadFile()  
    {
        try {
            
        
 if(isLoad){
        Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
        pasdata=new AmanPasDatabse_PasdataTable(z_connection); 
        pasFile = new AmanPasDatabse_PasdataFile(z_connection);
        VistTable = new AmanPasDatabse_Visit_table(z_connection);
        pasReenue = new Aman_finish_pasRevenue(z_connection);
        Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview_name(""));
 OtherMethods o = new OtherMethods();
        o.JTableformat(Tble_Show_dataFile);
 }} catch (Exception e) {
            System.err.println(e);
        }   

 } 
        
 void TxtVent(){
  
 txtSearchName_Pas_Data.getDocument().addDocumentListener(new DocumentListener() {
 String s = ""; 
     
     @Override
   
    public void insertUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText();
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
  
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText(); 
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
     s = txtSearchName_Pas_Data.getText();    
  
    }
   
    
});
 
    
 }
 
 void pas_SaarchName(String s) throws SQLException, ParseException{
Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
 
 }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pnlPas_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tble_Show_dataFile = new javax.swing.JTable();
        pnl_Tab_PasData = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        pnl_Main_Data = new javax.swing.JPanel();
        LblSet_Data = new javax.swing.JLabel();
        LblName_Pas_Data = new javax.swing.JLabel();
        LblID_Pas_Data = new javax.swing.JLabel();
        LblDateBirth_Pas_Data = new javax.swing.JLabel();
        LblGender_Pas_Data = new javax.swing.JLabel();
        LblJob_Pas_Data = new javax.swing.JLabel();
        LblAddress_Pas_Data = new javax.swing.JLabel();
        LblGov_Pas_Data = new javax.swing.JLabel();
        LblMarital_Status_Pas_Data = new javax.swing.JLabel();
        LblMob_Pas_Data = new javax.swing.JLabel();
        LblHome_Phone_Pas_Data = new javax.swing.JLabel();
        txtName_Pas_Data = new javax.swing.JTextField();
        txtID_Pas_Data = new javax.swing.JTextField();
        txtGender_Pas_Data = new javax.swing.JTextField();
        txtAddress_Pas_Data = new javax.swing.JTextField();
        txtJob_Pas_Data = new javax.swing.JTextField();
        txtGov_Pas_Data = new javax.swing.JTextField();
        txtMarital_Status_Pas_Data = new javax.swing.JTextField();
        txtMob_Pas_Data = new javax.swing.JTextField();
        txtHome_Phone_Pas_Data = new javax.swing.JTextField();
        LblAge_Pas_Data = new javax.swing.JLabel();
        txtAge_Pas_Data = new javax.swing.JTextField();
        ClnDateBirth_Pas_Data = new org.jdesktop.swingx.JXDatePicker();
        jPanel4 = new javax.swing.JPanel();
        pnl_Other_Data = new javax.swing.JPanel();
        Lbl_OtherData = new javax.swing.JLabel();
        LblNum_Vist_otherData = new javax.swing.JLabel();
        LblSrv_Type_otherData = new javax.swing.JLabel();
        LblExam_Type_otherData = new javax.swing.JLabel();
        LblTreat_Doc_otherData = new javax.swing.JLabel();
        LblCnvrt_Doc_otherData = new javax.swing.JLabel();
        LblExam_Value_otherData = new javax.swing.JLabel();
        LblDate_Vist_otherData = new javax.swing.JLabel();
        LblTimeVist_otherData = new javax.swing.JLabel();
        LblLst_dateVist_otherData = new javax.swing.JLabel();
        LblDrugs_otherData = new javax.swing.JLabel();
        LblTreat_Requst_otherData = new javax.swing.JLabel();
        LblTreat_Request_otherData = new javax.swing.JLabel();
        LblTreat_Rquest_otherData = new javax.swing.JLabel();
        LblTraet_Rquest_otherData = new javax.swing.JLabel();
        txtNum_Vist_otherData = new javax.swing.JTextField();
        txtSrv_Type_otherData = new javax.swing.JTextField();
        txtExam_Type_otherData = new javax.swing.JTextField();
        txtTreat_Doc_otherData = new javax.swing.JTextField();
        txtCnvrt_Doc_otherData = new javax.swing.JTextField();
        txtExam_Value_otherData = new javax.swing.JTextField();
        txtDate_Vist_otherData = new javax.swing.JTextField();
        txtTime_Vist_otherData = new javax.swing.JTextField();
        txtNxt_dateVist_otherData = new javax.swing.JTextField();
        txtDrugs_otherData = new javax.swing.JTextField();
        txtTreat_Request2_otherData = new javax.swing.JTextField();
        txtTreat_Rquest1_otherData = new javax.swing.JTextField();
        txtTreat_Rquest3_otherData = new javax.swing.JTextField();
        txtTreat_Rquest4_otherData = new javax.swing.JTextField();
        LblDetails_OtherData = new javax.swing.JLabel();
        txtDetails_OtherData = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        pnlPas_Status = new javax.swing.JPanel();
        LblPas_Status = new javax.swing.JLabel();
        LblHeight_Pas_Status = new javax.swing.JLabel();
        LblWeight_Pas_Status = new javax.swing.JLabel();
        LblSugar_Pas_Status = new javax.swing.JLabel();
        LblBlood_Pas_Status = new javax.swing.JLabel();
        LblHymoglopin_Pas_Status = new javax.swing.JLabel();
        LblRight_Eye_Pas_Status = new javax.swing.JLabel();
        LblLeft_Eye_Pas_Status = new javax.swing.JLabel();
        txtHeight_Pas_Status = new javax.swing.JTextField();
        txtHymoglopin_Pas_Status = new javax.swing.JTextField();
        txtWeight_Pas_Status = new javax.swing.JTextField();
        txtRight_Eye_Pas_Status = new javax.swing.JTextField();
        txtSugar_Pas_Status = new javax.swing.JTextField();
        txtLeft_Eye_Pas_Status = new javax.swing.JTextField();
        txtBlood_Pas_Status = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        pnl_Visit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVist_Num = new javax.swing.JTextField();
        Cmp_Time = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Cmp_Doctor = new javax.swing.JComboBox<>();
        Clnd_Date = new projict_Class.ACalender();
        Cmp_ExamType = new projict_Class.ACombobox();
        txtExamValue = new projict_Class.TxTf();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_cash = new projict_Class.TxTf();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        jButton6.setText("اضافة جديد");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("تعديل ملف");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data))
                .addGap(190, 190, 190))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addGap(7, 7, 7)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblSearch_ID_Pas_Data)
                            .addComponent(jButton7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSearchID_Pas_Data)))
                .addContainerGap())
        );

        Tble_Show_dataFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "إسم المريض"
            }
        ));
        Tble_Show_dataFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tble_Show_dataFileFocusGained(evt);
            }
        });
        Tble_Show_dataFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_Show_dataFileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tble_Show_dataFile);

        javax.swing.GroupLayout pnlPas_TableLayout = new javax.swing.GroupLayout(pnlPas_Table);
        pnlPas_Table.setLayout(pnlPas_TableLayout);
        pnlPas_TableLayout.setHorizontalGroup(
            pnlPas_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlPas_TableLayout.setVerticalGroup(
            pnlPas_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPas_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        LblSet_Data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblSet_Data.setText("البيانات الأساسية :");

        LblName_Pas_Data.setText("الاسم :");

        LblID_Pas_Data.setText("رقم المريض :");

        LblDateBirth_Pas_Data.setText("تاريخ الميلاد :");

        LblGender_Pas_Data.setText("الجنس :");

        LblJob_Pas_Data.setText("الوظيفة :");

        LblAddress_Pas_Data.setText("العنوان :");

        LblGov_Pas_Data.setText("المحافظة :");

        LblMarital_Status_Pas_Data.setText("الحالة الاجتماعية :");

        LblMob_Pas_Data.setText("موبايل :");

        LblHome_Phone_Pas_Data.setText("ت المنزل :");

        txtName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_Pas_DataActionPerformed(evt);
            }
        });

        txtJob_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJob_Pas_DataActionPerformed(evt);
            }
        });

        LblAge_Pas_Data.setText("السن:");

        javax.swing.GroupLayout pnl_Main_DataLayout = new javax.swing.GroupLayout(pnl_Main_Data);
        pnl_Main_Data.setLayout(pnl_Main_DataLayout);
        pnl_Main_DataLayout.setHorizontalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblSet_Data)
                .addGap(56, 56, 56))
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Main_DataLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ClnDateBirth_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(LblName_Pas_Data)
                                .addGap(79, 79, 79)
                                .addComponent(txtID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblID_Pas_Data)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGov_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarital_Status_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblHome_Phone_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                        .addComponent(LblGov_Pas_Data)
                                        .addGap(14, 14, 14))))
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblMarital_Status_Pas_Data)))
                        .addGap(31, 31, 31)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LblMob_Pas_Data)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblAddress_Pas_Data)
                                    .addComponent(LblJob_Pas_Data))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGender_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDateBirth_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblGender_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblAge_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Main_DataLayout.setVerticalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblSet_Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblID_Pas_Data)
                    .addComponent(txtID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblName_Pas_Data)
                    .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGov_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblGov_Pas_Data)
                    .addComponent(txtJob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblJob_Pas_Data)
                    .addComponent(ClnDateBirth_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDateBirth_Pas_Data))
                .addGap(34, 34, 34)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarital_Status_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMarital_Status_Pas_Data)
                    .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAddress_Pas_Data)
                    .addComponent(txtGender_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblGender_Pas_Data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblAge_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblMob_Pas_Data)
                            .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblHome_Phone_Pas_Data))
                        .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnl_Main_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("البيانات الأساسية", jPanel3);

        pnl_Other_Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lbl_OtherData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lbl_OtherData.setText("بيانات أخرى :");

        LblNum_Vist_otherData.setText("رقم الزيارة :");

        LblSrv_Type_otherData.setText("نوع الخدمة :");

        LblExam_Type_otherData.setText("نوع الكشف :");

        LblTreat_Doc_otherData.setText("الطبيب المعالج :");

        LblCnvrt_Doc_otherData.setText("الطبيب المحوّل :");

        LblExam_Value_otherData.setText("قيمة الكشف :");

        LblDate_Vist_otherData.setText("تاريخ الزيارة :");

        LblTimeVist_otherData.setText("وقت الزيارة :");

        LblLst_dateVist_otherData.setText("تاريخ الزيارة القادمة :");

        LblDrugs_otherData.setText("الأدوية :");

        LblTreat_Requst_otherData.setText("حالة الطلب 1 :");

        LblTreat_Request_otherData.setText("حالة الطلب 2 :");

        LblTreat_Rquest_otherData.setText("حالة الطلب 3 :");

        LblTraet_Rquest_otherData.setText("حالة الطلب 4 :");

        txtTreat_Rquest1_otherData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreat_Rquest1_otherDataActionPerformed(evt);
            }
        });

        LblDetails_OtherData.setText("التفاصيل :");

        javax.swing.GroupLayout pnl_Other_DataLayout = new javax.swing.GroupLayout(pnl_Other_Data);
        pnl_Other_Data.setLayout(pnl_Other_DataLayout);
        pnl_Other_DataLayout.setHorizontalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addComponent(txtTreat_Rquest4_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblTraet_Rquest_otherData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTreat_Request2_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblTreat_Request_otherData))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDate_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTime_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNxt_dateVist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblTimeVist_otherData)
                                    .addComponent(LblDate_Vist_otherData))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addComponent(LblLst_dateVist_otherData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTreat_Doc_otherData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnvrt_Doc_otherData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExam_Value_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblCnvrt_Doc_otherData)
                                .addComponent(LblExam_Value_otherData))
                            .addComponent(LblTreat_Doc_otherData))
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtExam_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblExam_Type_otherData)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtSrv_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblSrv_Type_otherData)
                                        .addGap(8, 8, 8))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtNum_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblNum_Vist_otherData)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lbl_OtherData))
                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDetails_OtherData)
                            .addComponent(txtTreat_Rquest3_otherData, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTreat_Rquest_otherData)
                            .addComponent(LblDetails_OtherData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDrugs_otherData)
                            .addComponent(txtTreat_Rquest1_otherData, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTreat_Requst_otherData)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                .addComponent(LblDrugs_otherData)
                                .addContainerGap())))))
        );
        pnl_Other_DataLayout.setVerticalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_OtherData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblTreat_Doc_otherData)
                        .addComponent(txtTreat_Doc_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblDate_Vist_otherData))
                    .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNum_Vist_otherData)
                        .addComponent(txtNum_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSrv_Type_otherData)
                    .addComponent(LblCnvrt_Doc_otherData)
                    .addComponent(LblTimeVist_otherData)
                    .addComponent(txtSrv_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnvrt_Doc_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNxt_dateVist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblExam_Type_otherData)
                        .addComponent(LblExam_Value_otherData)
                        .addComponent(txtExam_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtExam_Value_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblLst_dateVist_otherData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDrugs_otherData)
                    .addComponent(txtDrugs_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDetails_OtherData)
                    .addComponent(txtDetails_OtherData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreat_Rquest1_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTreat_Requst_otherData)
                    .addComponent(LblTreat_Rquest_otherData)
                    .addComponent(txtTreat_Rquest3_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreat_Request2_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTreat_Request_otherData)
                    .addComponent(LblTraet_Rquest_otherData)
                    .addComponent(txtTreat_Rquest4_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Other_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Other_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("بيانات أخرى", jPanel4);

        LblPas_Status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblPas_Status.setText("حالة المريض :");

        LblHeight_Pas_Status.setText("الطول :");

        LblWeight_Pas_Status.setText("الوزن :");

        LblSugar_Pas_Status.setText("السكر :");

        LblBlood_Pas_Status.setText("فصيلة الدم :");

        LblHymoglopin_Pas_Status.setText("الهيموجلبين :");

        LblRight_Eye_Pas_Status.setText("العين اليمنى :");

        LblLeft_Eye_Pas_Status.setText("العين اليسرى :");

        javax.swing.GroupLayout pnlPas_StatusLayout = new javax.swing.GroupLayout(pnlPas_Status);
        pnlPas_Status.setLayout(pnlPas_StatusLayout);
        pnlPas_StatusLayout.setHorizontalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPas_StatusLayout.createSequentialGroup()
                        .addComponent(txtBlood_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                        .addComponent(LblBlood_Pas_Status)
                                        .addGap(199, 199, 199))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPas_StatusLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblLeft_Eye_Pas_Status)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(LblRight_Eye_Pas_Status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHymoglopin_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LblSugar_Pas_Status)
                                .addGap(18, 18, 18)
                                .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblWeight_Pas_Status)
                                .addGap(18, 18, 18)
                                .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblHeight_Pas_Status)
                            .addComponent(LblHymoglopin_Pas_Status)))
                    .addComponent(LblPas_Status, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlPas_StatusLayout.setVerticalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LblPas_Status)
                .addGap(18, 18, 18)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHeight_Pas_Status)
                    .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblWeight_Pas_Status)
                    .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSugar_Pas_Status)
                    .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBlood_Pas_Status)
                    .addComponent(txtBlood_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHymoglopin_Pas_Status)
                    .addComponent(txtHymoglopin_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRight_Eye_Pas_Status)
                    .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblLeft_Eye_Pas_Status)
                    .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(pnlPas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlPas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("حالة المريض", jPanel5);

        pnl_Visit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_Visit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnl_VisitComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("الفحص والزيارات :");

        jLabel3.setText("رقم الزيارة :");

        jLabel4.setText("وقت الزيارة :");

        jLabel6.setText("نوع الكشف :");

        jLabel7.setText("بتاريخ :");

        jLabel8.setText("قيمة الكشف :");

        Cmp_Time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "صباحي", "مسائي" }));

        jLabel9.setText("اسم الطبيب");

        Cmp_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmp_DoctorActionPerformed(evt);
            }
        });

        Cmp_ExamType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmp_ExamTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_VisitLayout = new javax.swing.GroupLayout(pnl_Visit);
        pnl_Visit.setLayout(pnl_VisitLayout);
        pnl_VisitLayout.setHorizontalGroup(
            pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VisitLayout.createSequentialGroup()
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cmp_Time, 0, 383, Short.MAX_VALUE)
                            .addComponent(Clnd_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnl_VisitLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_VisitLayout.createSequentialGroup()
                                .addComponent(Cmp_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_VisitLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(txtVist_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(6, 6, 6))))
                            .addGroup(pnl_VisitLayout.createSequentialGroup()
                                .addComponent(txtExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                                        .addComponent(Cmp_ExamType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(251, 251, 251)))))))
                .addContainerGap())
        );
        pnl_VisitLayout.setVerticalGroup(
            pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VisitLayout.createSequentialGroup()
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VisitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVist_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Cmp_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(Cmp_ExamType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Cmp_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(Clnd_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton2.setText("حجز هاتفي");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("حجز حضور");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("حجز و سداد جزءي");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("حجز و سداد كلي");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_Visit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Visit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(txt_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("الفحص والزيارات", jPanel6);

        javax.swing.GroupLayout pnl_Tab_PasDataLayout = new javax.swing.GroupLayout(pnl_Tab_PasData);
        pnl_Tab_PasData.setLayout(pnl_Tab_PasDataLayout);
        pnl_Tab_PasDataLayout.setHorizontalGroup(
            pnl_Tab_PasDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Tab_PasDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );
        pnl_Tab_PasDataLayout.setVerticalGroup(
            pnl_Tab_PasDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Tab_PasDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_Tab_PasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPas_Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPas_Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Tab_PasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtJob_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJob_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJob_Pas_DataActionPerformed

    private void txtName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_Pas_DataActionPerformed
 
// TODO add your handling code here:
    }//GEN-LAST:event_txtName_Pas_DataActionPerformed

    private void Tble_Show_dataFileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileFocusGained



        // TODO add your handling code here:
    }//GEN-LAST:event_Tble_Show_dataFileFocusGained

    private void Tble_Show_dataFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileMouseClicked
      
        int row = Tble_Show_dataFile.rowAtPoint(evt.getPoint());

        int col = Tble_Show_dataFile.columnAtPoint(evt.getPoint());

    String valueInCell = (String)Tble_Show_dataFile.getValueAt(row, col);

    String id = pasdata.dataTableShow.getvalue(row, pasdata.ID);
String name = pasdata.dataTableShow.getvalue(row, pasdata.Name);
    System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
Pas_id = id ; Pas_Name = name ;
    try {            

            LoadPasData(id);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    //LoadpasFile

    try {            

            LoadPasFile(id);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_Tble_Show_dataFileMouseClicked

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

          // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed
void add_Vist(String VistCase){
OtherMethods o = new OtherMethods();
        
        try {
            
      
  VistTable.Insert_newVisit(Cmp_Time.getSelectedItem()+"",
           o.ChangeFrmat(Clnd_Date.getDate()),
        Cmp_Doctor.getSelectedItem()+"",Cmp_ExamType.getSelectedItem()+"",Pas_Name,VistCase,Pas_id,txtExamValue.getText());
        
           } catch (Exception e) {
               System.err.println("Add vist error"+e);
        }
}

 
    private void txtTreat_Rquest1_otherDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreat_Rquest1_otherDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreat_Rquest1_otherDataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add_Vist(VistTable.HAGZ_bY_pHONE);
 try { 
     pasReenue.insert_ExmapRevenue(Clnd_Date,Cmp_ExamType, txtExamValue
      , Pas_Name , Pas_id, "00.00" );
 }catch(Exception e){
 
     System.out.println(" insert reevenu error " + e );
 }   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 add_Vist(VistTable.HAGZ_BY_HODOR);      
 try { 
     pasReenue.insert_ExmapRevenue(Clnd_Date,Cmp_ExamType, txtExamValue
      , Pas_Name , Pas_id, "00.00" );
 }catch(Exception e){
 
     System.out.println(" insert reevenu error " + e );
 }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 add_Vist(VistTable.HAGZ_BY_SADAD);
    
try { 
     pasReenue.insert_ExmapRevenue(Clnd_Date,Cmp_ExamType, txtExamValue
      , Pas_Name , Pas_id, txt_cash.getValue());
 }catch(Exception e){
 
     System.out.println(" insert reevenu error " + e );
 } 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Frm_insertPasData iData = new Frm_insertPasData();
  
 try { iData.setisliad(false, "");
}catch(Exception x){}
iData.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Frm_insertPasData iData = new Frm_insertPasData();
try { 
    if(Pas_id == ""){Pas_id=1+"";}
    iData.setisliad(true, Pas_id);
}catch(Exception x){}
 
iData.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pnl_VisitComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnl_VisitComponentShown
   
    }//GEN-LAST:event_pnl_VisitComponentShown

    private void Cmp_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmp_DoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmp_DoctorActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown


        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void Cmp_ExamTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmp_ExamTypeActionPerformed
comp_exampselect();
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmp_ExamTypeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

 try { 
     pasReenue.insert_ExmapRevenue(Clnd_Date,Cmp_ExamType, txtExamValue
      , Pas_Name , Pas_id, txtExamValue.getValue());
 }catch(Exception e){
 
     System.out.println(" insert reevenu error " + e );
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
  Z_connection z_connection=new Z_connection("aman_doctordatabase","root","");
    AmanDatabse_doctorService docService = new AmanDatabse_doctorService(z_connection);
    AmanDoctorDatabse_doctorData docdordata = new AmanDoctorDatabse_doctorData(z_connection);
  
    void comp_exampselect(){
         
         try {
  String s =   docService.LoadData_service(Cmp_ExamType.getSelectedItem()+"");
        txtExamValue.setText(s);
          
          System.out.println("geted");
// TODO add your handling code here:
        } catch (Exception ex) {
                  
        }
     }
    void Showcomboservice()  {
       try {
            docService.ComboFill(Cmp_ExamType, docService.service);
         docdordata.ComboFill(Cmp_Doctor, docdordata.Name);
        docService.ComboFill(Cmp_ExamType, docService.service);
         txtVist_Num.setText(VistTable.getVisetNom(Pas_id)+"");
         Date d = new Date(); 
         Clnd_Date.setDate(d );
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("fill compo error"+ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void LoadPasData(String id ) throws SQLException, ParseException
 {
     OtherMethods M=new OtherMethods();
     pasdata.LoadFile_id(id);
    // pasFile.dataShow.MoveLast();
     txtName_Pas_Data.setText(pasdata.getValue(pasdata.Name));
     txtID_Pas_Data.setText(pasdata.getValue(pasdata.ID));
ClnDateBirth_Pas_Data.setDate(M.GetStringVal(pasdata.getValue(pasdata.DateBirth)));
   txtGender_Pas_Data.setText(pasdata.getValue(pasdata.Gender));
    txtAge_Pas_Data.setText(pasdata.getValue(pasdata.Age));
    txtJob_Pas_Data.setText(pasdata.getValue(pasdata.Job));
    txtAddress_Pas_Data.setText(pasdata.getValue(pasdata.Address));
    txtMob_Pas_Data.setText(pasdata.getValue(pasdata.Mob));
    txtGov_Pas_Data.setText(pasdata.getValue(pasdata.Gov));
    txtMarital_Status_Pas_Data.setText(pasdata.getValue(pasdata.Status));
    txtHome_Phone_Pas_Data.setText(pasdata.getValue(pasdata.HomePhone));
    txtWeight_Pas_Status.setText(pasdata.getValue(pasdata.Weight));
    txtHeight_Pas_Status.setText(pasdata.getValue(pasdata.Height));
    txtSugar_Pas_Status.setText(pasdata.getValue(pasdata.Suger));
    txtBlood_Pas_Status.setText(pasdata.getValue(pasdata.Blood));
    txtHymoglopin_Pas_Status.setText(pasdata.getValue(pasdata.hymoglobin));
 String Rsee,LSee,see;
 see=pasdata.getValue(pasdata.See);
 String TotalSee[]=see.split("/");
 Rsee=TotalSee[0].substring(2);
 LSee=TotalSee[1].substring(2);
 txtRight_Eye_Pas_Status.setText(Rsee);
 txtLeft_Eye_Pas_Status.setText(LSee); 

 
 
 
 //viset no 
       txtVist_Num.setText(VistTable.getVisetNom(Pas_id)+"");
   
 }
 
 void LoadPasFile(String file_id) throws SQLException, ParseException{
        pasFile.LoadFile_id(file_id);

  txtNum_Vist_otherData.setText(pasFile.getValue(pasFile.NumVist));
 txtSrv_Type_otherData.setText(pasFile.getValue(pasFile.TypeService));
 txtExam_Type_otherData.setText(pasFile.getValue(pasFile.ExamType));
 txtTreat_Doc_otherData.setText(pasFile.getValue(pasFile.TreatDoctor));
txtCnvrt_Doc_otherData.setText(pasFile.getValue(pasFile.ConvertDoctor));
txtExam_Value_otherData.setText(pasFile.getValue(pasFile.ExamValue));
txtTime_Vist_otherData.setText(pasFile.getValue(pasFile.TimeVisit));
txtDetails_OtherData.setText(pasFile.getValue(pasFile.StatueDetails));
txtDrugs_otherData.setText(pasFile.getValue(pasFile.Drugs));
txtTreat_Rquest1_otherData.setText(pasFile.getValue(pasFile.TreatRequest1));
 }
 
 
 /// evenets 
 
 void compSelect(){
 
     if ( loaded ){return ; }
     Cmp_ExamType.addItemListener(new ItemListener() {
     @Override
     public void itemStateChanged(ItemEvent e) {
    
         comp_exampselect();
     }
 });
 
 }
 
 

 void Tapchange (){
 compSelect();
 jTabbedPane1.addChangeListener(new ChangeListener() {
    @Override
     public void stateChanged(ChangeEvent e) {
        System.out.println("Tab: " + jTabbedPane1.getSelectedIndex());
if (jTabbedPane1.getSelectedIndex() == 3 ){
Showcomboservice();

}      
        
// Prints the string 3 times if there are 3 tabs etc
    }

    
 });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker ClnDateBirth_Pas_Data;
    private projict_Class.ACalender Clnd_Date;
    private javax.swing.JComboBox<String> Cmp_Doctor;
    private projict_Class.ACombobox Cmp_ExamType;
    private javax.swing.JComboBox<String> Cmp_Time;
    private javax.swing.JLabel LblAddress_Pas_Data;
    private javax.swing.JLabel LblAge_Pas_Data;
    private javax.swing.JLabel LblBlood_Pas_Status;
    private javax.swing.JLabel LblCnvrt_Doc_otherData;
    private javax.swing.JLabel LblDateBirth_Pas_Data;
    private javax.swing.JLabel LblDate_Vist_otherData;
    private javax.swing.JLabel LblDetails_OtherData;
    private javax.swing.JLabel LblDrugs_otherData;
    private javax.swing.JLabel LblExam_Type_otherData;
    private javax.swing.JLabel LblExam_Value_otherData;
    private javax.swing.JLabel LblGender_Pas_Data;
    private javax.swing.JLabel LblGov_Pas_Data;
    private javax.swing.JLabel LblHeight_Pas_Status;
    private javax.swing.JLabel LblHome_Phone_Pas_Data;
    private javax.swing.JLabel LblHymoglopin_Pas_Status;
    private javax.swing.JLabel LblID_Pas_Data;
    private javax.swing.JLabel LblJob_Pas_Data;
    private javax.swing.JLabel LblLeft_Eye_Pas_Status;
    private javax.swing.JLabel LblLst_dateVist_otherData;
    private javax.swing.JLabel LblMarital_Status_Pas_Data;
    private javax.swing.JLabel LblMob_Pas_Data;
    private javax.swing.JLabel LblName_Pas_Data;
    private javax.swing.JLabel LblNum_Vist_otherData;
    private javax.swing.JLabel LblPas_Status;
    private javax.swing.JLabel LblRight_Eye_Pas_Status;
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel LblSet_Data;
    private javax.swing.JLabel LblSrv_Type_otherData;
    private javax.swing.JLabel LblSugar_Pas_Status;
    private javax.swing.JLabel LblTimeVist_otherData;
    private javax.swing.JLabel LblTraet_Rquest_otherData;
    private javax.swing.JLabel LblTreat_Doc_otherData;
    private javax.swing.JLabel LblTreat_Request_otherData;
    private javax.swing.JLabel LblTreat_Requst_otherData;
    private javax.swing.JLabel LblTreat_Rquest_otherData;
    private javax.swing.JLabel LblWeight_Pas_Status;
    private javax.swing.JLabel Lbl_OtherData;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JTable Tble_Show_dataFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlPas_Status;
    private javax.swing.JPanel pnlPas_Table;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private javax.swing.JPanel pnl_Main_Data;
    private javax.swing.JPanel pnl_Other_Data;
    private javax.swing.JPanel pnl_Tab_PasData;
    private javax.swing.JPanel pnl_Visit;
    private javax.swing.JTextField txtAddress_Pas_Data;
    private javax.swing.JTextField txtAge_Pas_Data;
    private javax.swing.JTextField txtBlood_Pas_Status;
    private javax.swing.JTextField txtCnvrt_Doc_otherData;
    private javax.swing.JTextField txtDate_Vist_otherData;
    private javax.swing.JTextField txtDetails_OtherData;
    private javax.swing.JTextField txtDrugs_otherData;
    private projict_Class.TxTf txtExamValue;
    private javax.swing.JTextField txtExam_Type_otherData;
    private javax.swing.JTextField txtExam_Value_otherData;
    private javax.swing.JTextField txtGender_Pas_Data;
    private javax.swing.JTextField txtGov_Pas_Data;
    private javax.swing.JTextField txtHeight_Pas_Status;
    private javax.swing.JTextField txtHome_Phone_Pas_Data;
    private javax.swing.JTextField txtHymoglopin_Pas_Status;
    private javax.swing.JTextField txtID_Pas_Data;
    private javax.swing.JTextField txtJob_Pas_Data;
    private javax.swing.JTextField txtLeft_Eye_Pas_Status;
    private javax.swing.JTextField txtMarital_Status_Pas_Data;
    private javax.swing.JTextField txtMob_Pas_Data;
    private javax.swing.JTextField txtName_Pas_Data;
    private javax.swing.JTextField txtNum_Vist_otherData;
    private javax.swing.JTextField txtNxt_dateVist_otherData;
    private javax.swing.JTextField txtRight_Eye_Pas_Status;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    private javax.swing.JTextField txtSrv_Type_otherData;
    private javax.swing.JTextField txtSugar_Pas_Status;
    private javax.swing.JTextField txtTime_Vist_otherData;
    private javax.swing.JTextField txtTreat_Doc_otherData;
    private javax.swing.JTextField txtTreat_Request2_otherData;
    private javax.swing.JTextField txtTreat_Rquest1_otherData;
    private javax.swing.JTextField txtTreat_Rquest3_otherData;
    private javax.swing.JTextField txtTreat_Rquest4_otherData;
    private javax.swing.JTextField txtVist_Num;
    private javax.swing.JTextField txtWeight_Pas_Status;
    private projict_Class.TxTf txt_cash;
    // End of variables declaration//GEN-END:variables
}
