
import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mysql_data_link.ZeftawyTools.OtherMethods;
import mysql_data_link.ZeftawyTools.Z_connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aman
 */
public class pnl_pasReport extends javax.swing.JPanel {

    public String file_id="1";
    public boolean isLoad=true;
  boolean  loaded = false  ; 
 AmanPasDatabse_PasdataTable pasdata;
 AmanPasDatabse_PasdataFile pasFile;
 AmanPasDatabse_Visit_table VistTable ;
 Aman_finish_pasRevenue pasRevenue;
 String Pas_id  , Pas_Name  ;
    public pnl_pasReport() {
        loaded = false ;
        initComponents();
        try{
        loadFile();  
        TxtVent();}
        catch(Exception e){System.out.println(e);}
    
    
            
jTabbedPane1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

loaded = true ; 
        
 
  }
    
 public void loadFile() throws SQLException, ParseException  
    {                  
 if(isLoad){
        Z_connection z_connection=new Z_connection("aman_pasiontdatabase","root","");
        pasdata=new AmanPasDatabse_PasdataTable(z_connection); 
        pasFile = new AmanPasDatabse_PasdataFile(z_connection);
        pasRevenue=new Aman_finish_pasRevenue(z_connection);
        Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview_name(""));
 OtherMethods o = new OtherMethods();
        o.JTableformat(Tble_Show_dataFile);
 }else{} 

 } 
        
 void TxtVent(){
  
 txtSearchName_Pas_Data.getDocument().addDocumentListener(new DocumentListener() {
 String s = ""; 
     
 
 void pas_SaarchName(String s) throws SQLException, ParseException{
Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
 
} 

      @Override
   
    public void insertUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText();
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
  
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       s = txtSearchName_Pas_Data.getText(); 
     try {
         pas_SaarchName(s);
     } catch (SQLException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
     s = txtSearchName_Pas_Data.getText();    
  
    }
   
    
});
 
    
 }
 
 void pas_SaarchName(String s) throws SQLException, ParseException{
Tble_Show_dataFile.setModel(pasdata.LoadFile_id_showTableview(s,pasdata.Name));
 
 }   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSearch_Pas_Data = new javax.swing.JPanel();
        Lbl_Search_Name_pas_Data = new javax.swing.JLabel();
        LblSearch_ID_Pas_Data = new javax.swing.JLabel();
        txtSearchName_Pas_Data = new javax.swing.JTextField();
        txtSearchID_Pas_Data = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tble_Show_dataFile = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        pnl_Main_Data = new javax.swing.JPanel();
        LblSet_Data = new javax.swing.JLabel();
        LblName_Pas_Data = new javax.swing.JLabel();
        LblID_Pas_Data = new javax.swing.JLabel();
        LblDateBirth_Pas_Data = new javax.swing.JLabel();
        LblGender_Pas_Data = new javax.swing.JLabel();
        LblJob_Pas_Data = new javax.swing.JLabel();
        LblAddress_Pas_Data = new javax.swing.JLabel();
        LblGov_Pas_Data = new javax.swing.JLabel();
        LblMarital_Status_Pas_Data = new javax.swing.JLabel();
        LblMob_Pas_Data = new javax.swing.JLabel();
        LblHome_Phone_Pas_Data = new javax.swing.JLabel();
        txtName_Pas_Data = new javax.swing.JTextField();
        txtID_Pas_Data = new javax.swing.JTextField();
        txtGender_Pas_Data = new javax.swing.JTextField();
        txtAddress_Pas_Data = new javax.swing.JTextField();
        txtJob_Pas_Data = new javax.swing.JTextField();
        txtGov_Pas_Data = new javax.swing.JTextField();
        txtMarital_Status_Pas_Data = new javax.swing.JTextField();
        txtMob_Pas_Data = new javax.swing.JTextField();
        txtHome_Phone_Pas_Data = new javax.swing.JTextField();
        LblAge_Pas_Data = new javax.swing.JLabel();
        txtAge_Pas_Data = new javax.swing.JTextField();
        ClnDateBirth_Pas_Data = new org.jdesktop.swingx.JXDatePicker();
        jPanel4 = new javax.swing.JPanel();
        pnl_Other_Data = new javax.swing.JPanel();
        Lbl_OtherData = new javax.swing.JLabel();
        LblNum_Vist_otherData = new javax.swing.JLabel();
        LblSrv_Type_otherData = new javax.swing.JLabel();
        LblExam_Type_otherData = new javax.swing.JLabel();
        LblTreat_Doc_otherData = new javax.swing.JLabel();
        LblCnvrt_Doc_otherData = new javax.swing.JLabel();
        LblExam_Value_otherData = new javax.swing.JLabel();
        LblDate_Vist_otherData = new javax.swing.JLabel();
        LblTimeVist_otherData = new javax.swing.JLabel();
        LblLst_dateVist_otherData = new javax.swing.JLabel();
        LblDrugs_otherData = new javax.swing.JLabel();
        LblTreat_Requst_otherData = new javax.swing.JLabel();
        LblTreat_Request_otherData = new javax.swing.JLabel();
        LblTreat_Rquest_otherData = new javax.swing.JLabel();
        LblTraet_Rquest_otherData = new javax.swing.JLabel();
        txtNum_Vist_otherData = new javax.swing.JTextField();
        txtSrv_Type_otherData = new javax.swing.JTextField();
        txtExam_Type_otherData = new javax.swing.JTextField();
        txtTreat_Doc_otherData = new javax.swing.JTextField();
        txtCnvrt_Doc_otherData = new javax.swing.JTextField();
        txtExam_Value_otherData = new javax.swing.JTextField();
        txtDate_Vist_otherData = new javax.swing.JTextField();
        txtTime_Vist_otherData = new javax.swing.JTextField();
        txtNxt_dateVist_otherData = new javax.swing.JTextField();
        txtDrugs_otherData = new javax.swing.JTextField();
        txtTreat_Request2_otherData = new javax.swing.JTextField();
        txtTreat_Rquest1_otherData = new javax.swing.JTextField();
        txtTreat_Rquest3_otherData = new javax.swing.JTextField();
        txtTreat_Rquest4_otherData = new javax.swing.JTextField();
        LblDetails_OtherData = new javax.swing.JLabel();
        txtDetails_OtherData = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        pnlPas_Status = new javax.swing.JPanel();
        LblPas_Status = new javax.swing.JLabel();
        LblHeight_Pas_Status = new javax.swing.JLabel();
        LblWeight_Pas_Status = new javax.swing.JLabel();
        LblSugar_Pas_Status = new javax.swing.JLabel();
        LblBlood_Pas_Status = new javax.swing.JLabel();
        LblHymoglopin_Pas_Status = new javax.swing.JLabel();
        LblRight_Eye_Pas_Status = new javax.swing.JLabel();
        LblLeft_Eye_Pas_Status = new javax.swing.JLabel();
        txtHeight_Pas_Status = new javax.swing.JTextField();
        txtHymoglopin_Pas_Status = new javax.swing.JTextField();
        txtWeight_Pas_Status = new javax.swing.JTextField();
        txtRight_Eye_Pas_Status = new javax.swing.JTextField();
        txtSugar_Pas_Status = new javax.swing.JTextField();
        txtLeft_Eye_Pas_Status = new javax.swing.JTextField();
        txtBlood_Pas_Status = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        pnl_Visit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aLable2 = new projict_Class.ALable();
        aLable3 = new projict_Class.ALable();
        aLable4 = new projict_Class.ALable();
        aLable5 = new projict_Class.ALable();
        aLable6 = new projict_Class.ALable();
        aLable7 = new projict_Class.ALable();
        aLable8 = new projict_Class.ALable();
        aLable9 = new projict_Class.ALable();
        aLable10 = new projict_Class.ALable();
        aLable11 = new projict_Class.ALable();
        txt_ExamValue = new projict_Class.TxTf();
        txt_pasValue = new projict_Class.TxTf();
        txt_InsValue = new projict_Class.TxTf();
        txt_ope = new projict_Class.TxTf();
        txt_Consum = new projict_Class.TxTf();
        txt_srv = new projict_Class.TxTf();
        txt_Total = new projict_Class.TxTf();
        txt_percent = new projict_Class.TxTf();
        txt_ExamType = new projict_Class.TxTf();
        txtExamDate = new projict_Class.TxTf();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tble_pasRevenue1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        Lbl_Search_Name_pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Search_Name_pas_Data.setText("الاسم :");

        LblSearch_ID_Pas_Data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSearch_ID_Pas_Data.setText("رقم الملف :");

        txtSearchName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName_Pas_DataActionPerformed(evt);
            }
        });

        txtSearchID_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchID_Pas_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch_Pas_DataLayout = new javax.swing.GroupLayout(pnlSearch_Pas_Data);
        pnlSearch_Pas_Data.setLayout(pnlSearch_Pas_DataLayout);
        pnlSearch_Pas_DataLayout.setHorizontalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(LblSearch_ID_Pas_Data))
                .addGap(35, 35, 35))
        );
        pnlSearch_Pas_DataLayout.setVerticalGroup(
            pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Search_Name_pas_Data)
                    .addComponent(txtSearchName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlSearch_Pas_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addComponent(LblSearch_ID_Pas_Data)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(pnlSearch_Pas_DataLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSearchID_Pas_Data, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Tble_Show_dataFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "إسم المريض"
            }
        ));
        Tble_Show_dataFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tble_Show_dataFileFocusGained(evt);
            }
        });
        Tble_Show_dataFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_Show_dataFileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tble_Show_dataFile);

        LblSet_Data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblSet_Data.setText("البيانات الأساسية :");

        LblName_Pas_Data.setText("الاسم :");

        LblID_Pas_Data.setText("رقم المريض :");

        LblDateBirth_Pas_Data.setText("تاريخ الميلاد :");

        LblGender_Pas_Data.setText("الجنس :");

        LblJob_Pas_Data.setText("الوظيفة :");

        LblAddress_Pas_Data.setText("العنوان :");

        LblGov_Pas_Data.setText("المحافظة :");

        LblMarital_Status_Pas_Data.setText("الحالة الاجتماعية :");

        LblMob_Pas_Data.setText("موبايل :");

        LblHome_Phone_Pas_Data.setText("ت المنزل :");

        txtName_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_Pas_DataActionPerformed(evt);
            }
        });

        txtJob_Pas_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJob_Pas_DataActionPerformed(evt);
            }
        });

        LblAge_Pas_Data.setText("السن:");

        javax.swing.GroupLayout pnl_Main_DataLayout = new javax.swing.GroupLayout(pnl_Main_Data);
        pnl_Main_Data.setLayout(pnl_Main_DataLayout);
        pnl_Main_DataLayout.setHorizontalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblSet_Data)
                .addGap(56, 56, 56))
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Main_DataLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ClnDateBirth_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(LblName_Pas_Data)
                                .addGap(79, 79, 79)
                                .addComponent(txtID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblID_Pas_Data)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGov_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarital_Status_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblHome_Phone_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                                .addComponent(LblGov_Pas_Data)
                                                .addGap(14, 14, 14))))
                                    .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblMarital_Status_Pas_Data)))
                                .addGap(31, 31, 31)
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblJob_Pas_Data)
                                    .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LblMob_Pas_Data)
                                        .addComponent(LblAddress_Pas_Data)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGender_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_DataLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDateBirth_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblGender_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblAge_Pas_Data, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Main_DataLayout.setVerticalGroup(
            pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_DataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblSet_Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblID_Pas_Data)
                    .addComponent(txtID_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblName_Pas_Data)
                    .addComponent(txtName_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGov_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblGov_Pas_Data)
                    .addComponent(txtJob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblJob_Pas_Data)
                    .addComponent(ClnDateBirth_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDateBirth_Pas_Data))
                .addGap(34, 34, 34)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarital_Status_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMarital_Status_Pas_Data)
                    .addComponent(txtAddress_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAddress_Pas_Data)
                    .addComponent(txtGender_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblGender_Pas_Data))
                .addGap(18, 18, 18)
                .addGroup(pnl_Main_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAge_Pas_Data)
                    .addComponent(txtAge_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMob_Pas_Data)
                    .addComponent(txtMob_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHome_Phone_Pas_Data)
                    .addComponent(txtHome_Phone_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnl_Main_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("البيانات الأساسية", jPanel3);

        pnl_Other_Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lbl_OtherData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lbl_OtherData.setText("بيانات أخرى :");

        LblNum_Vist_otherData.setText("رقم الزيارة :");

        LblSrv_Type_otherData.setText("نوع الخدمة :");

        LblExam_Type_otherData.setText("نوع الكشف :");

        LblTreat_Doc_otherData.setText("الطبيب المعالج :");

        LblCnvrt_Doc_otherData.setText("الطبيب المحوّل :");

        LblExam_Value_otherData.setText("قيمة الكشف :");

        LblDate_Vist_otherData.setText("تاريخ الزيارة :");

        LblTimeVist_otherData.setText("وقت الزيارة :");

        LblLst_dateVist_otherData.setText("تاريخ الزيارة القادمة :");

        LblDrugs_otherData.setText("الأدوية :");

        LblTreat_Requst_otherData.setText("حالة الطلب 1 :");

        LblTreat_Request_otherData.setText("حالة الطلب 2 :");

        LblTreat_Rquest_otherData.setText("حالة الطلب 3 :");

        LblTraet_Rquest_otherData.setText("حالة الطلب 4 :");

        txtTreat_Rquest1_otherData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreat_Rquest1_otherDataActionPerformed(evt);
            }
        });

        LblDetails_OtherData.setText("التفاصيل :");

        javax.swing.GroupLayout pnl_Other_DataLayout = new javax.swing.GroupLayout(pnl_Other_Data);
        pnl_Other_Data.setLayout(pnl_Other_DataLayout);
        pnl_Other_DataLayout.setHorizontalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addComponent(txtTreat_Rquest4_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblTraet_Rquest_otherData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTreat_Request2_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblTreat_Request_otherData))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDate_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTime_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNxt_dateVist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblTimeVist_otherData)
                                    .addComponent(LblDate_Vist_otherData))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addComponent(LblLst_dateVist_otherData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTreat_Doc_otherData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnvrt_Doc_otherData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExam_Value_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblCnvrt_Doc_otherData)
                                .addComponent(LblExam_Value_otherData))
                            .addComponent(LblTreat_Doc_otherData))
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtExam_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblExam_Type_otherData)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                        .addComponent(txtSrv_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblSrv_Type_otherData)
                                        .addGap(8, 8, 8))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Other_DataLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtNum_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblNum_Vist_otherData)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lbl_OtherData))
                    .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDetails_OtherData)
                            .addComponent(txtTreat_Rquest3_otherData, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTreat_Rquest_otherData)
                            .addComponent(LblDetails_OtherData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDrugs_otherData)
                            .addComponent(txtTreat_Rquest1_otherData, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTreat_Requst_otherData)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createSequentialGroup()
                                .addComponent(LblDrugs_otherData)
                                .addContainerGap())))))
        );
        pnl_Other_DataLayout.setVerticalGroup(
            pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Other_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_OtherData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblTreat_Doc_otherData)
                        .addComponent(txtTreat_Doc_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblDate_Vist_otherData))
                    .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNum_Vist_otherData)
                        .addComponent(txtNum_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSrv_Type_otherData)
                    .addComponent(LblCnvrt_Doc_otherData)
                    .addComponent(LblTimeVist_otherData)
                    .addComponent(txtSrv_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTime_Vist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnvrt_Doc_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNxt_dateVist_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblExam_Type_otherData)
                        .addComponent(LblExam_Value_otherData)
                        .addComponent(txtExam_Type_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtExam_Value_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblLst_dateVist_otherData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDrugs_otherData)
                    .addComponent(txtDrugs_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDetails_OtherData)
                    .addComponent(txtDetails_OtherData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreat_Rquest1_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTreat_Requst_otherData)
                    .addComponent(LblTreat_Rquest_otherData)
                    .addComponent(txtTreat_Rquest3_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Other_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreat_Request2_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTreat_Request_otherData)
                    .addComponent(LblTraet_Rquest_otherData)
                    .addComponent(txtTreat_Rquest4_otherData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Other_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(pnl_Other_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("بيانات أخرى", jPanel4);

        LblPas_Status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblPas_Status.setText("حالة المريض :");

        LblHeight_Pas_Status.setText("الطول :");

        LblWeight_Pas_Status.setText("الوزن :");

        LblSugar_Pas_Status.setText("السكر :");

        LblBlood_Pas_Status.setText("فصيلة الدم :");

        LblHymoglopin_Pas_Status.setText("الهيموجلبين :");

        LblRight_Eye_Pas_Status.setText("العين اليمنى :");

        LblLeft_Eye_Pas_Status.setText("العين اليسرى :");

        javax.swing.GroupLayout pnlPas_StatusLayout = new javax.swing.GroupLayout(pnlPas_Status);
        pnlPas_Status.setLayout(pnlPas_StatusLayout);
        pnlPas_StatusLayout.setHorizontalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPas_StatusLayout.createSequentialGroup()
                        .addComponent(txtBlood_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                        .addComponent(LblBlood_Pas_Status)
                                        .addGap(199, 199, 199))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPas_StatusLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblLeft_Eye_Pas_Status)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(LblRight_Eye_Pas_Status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHymoglopin_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                                .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LblSugar_Pas_Status)
                                .addGap(18, 18, 18)
                                .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblWeight_Pas_Status)
                                .addGap(18, 18, 18)
                                .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblHeight_Pas_Status)
                            .addComponent(LblHymoglopin_Pas_Status)))
                    .addComponent(LblPas_Status, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlPas_StatusLayout.setVerticalGroup(
            pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPas_StatusLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LblPas_Status)
                .addGap(18, 18, 18)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHeight_Pas_Status)
                    .addComponent(txtHeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblWeight_Pas_Status)
                    .addComponent(txtWeight_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSugar_Pas_Status)
                    .addComponent(txtSugar_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBlood_Pas_Status)
                    .addComponent(txtBlood_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPas_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHymoglopin_Pas_Status)
                    .addComponent(txtHymoglopin_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRight_Eye_Pas_Status)
                    .addComponent(txtRight_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblLeft_Eye_Pas_Status)
                    .addComponent(txtLeft_Eye_Pas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(pnlPas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlPas_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("حالة المريض", jPanel5);

        pnl_Visit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_Visit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnl_VisitComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("كشف حساب المريض");

        aLable2.setText("تاريخ الكشف :");

        aLable3.setText("نوع الكشف :");

        aLable4.setText("قيمة الكشف :");

        aLable5.setText("قيمة المريض :");

        aLable6.setText("قيمة ش التأمين :");

        aLable7.setText("العمليـــــــات :");

        aLable8.setText("المستهلكـــــات :");

        aLable9.setText("الخدمــــات :");

        aLable10.setText("الإجمـــــــالى :");

        aLable11.setText("النسبـــــة :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_ope, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aLable7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_srv, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Consum, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_percent, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aLable8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLable9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLable10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLable11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ExamType, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExamDate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aLable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(aLable3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_InsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pasValue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aLable5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLable6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLable4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExamDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLable3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ExamType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Consum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLable4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ExamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLable5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pasValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLable11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_InsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLable6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Tble_pasRevenue1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tble_pasRevenue1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tble_pasRevenue1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tble_pasRevenue1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("الكشوفات والعمليات التى تمت للمريض :");

        javax.swing.GroupLayout pnl_VisitLayout = new javax.swing.GroupLayout(pnl_Visit);
        pnl_Visit.setLayout(pnl_VisitLayout);
        pnl_VisitLayout.setHorizontalGroup(
            pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(pnl_VisitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VisitLayout.createSequentialGroup()
                        .addGroup(pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnl_VisitLayout.setVerticalGroup(
            pnl_VisitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VisitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Visit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Visit, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("كشف حساب المريض", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addContainerGap())
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSearch_Pas_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName_Pas_DataActionPerformed

    private void txtSearchID_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchID_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchID_Pas_DataActionPerformed

    private void Tble_Show_dataFileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_Tble_Show_dataFileFocusGained

    private void Tble_Show_dataFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_Show_dataFileMouseClicked

        int row = Tble_Show_dataFile.rowAtPoint(evt.getPoint());

        int col = Tble_Show_dataFile.columnAtPoint(evt.getPoint());

        String valueInCell = (String)Tble_Show_dataFile.getValueAt(row, col);

        String id = pasdata.dataTableShow.getvalue(row, pasdata.ID);
        String name = pasdata.dataTableShow.getvalue(row, pasdata.Name);
        System.out.println("Row " +row + " Coll"+ col + "Value"+ valueInCell
            + "id is " + id );
        Pas_id = id ; Pas_Name = name ;
        try {

            LoadPasData(id);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        }

        //LoadpasFile

        try {

            LoadPasFile(id);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_Pas_Data.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        try {
            LoadPasRevenue(id);
        } catch (SQLException ex) {
            Logger.getLogger(pnl_pasReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(pnl_pasReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Tble_Show_dataFileMouseClicked

        void LoadPasData(String id ) throws SQLException, ParseException
 {
     OtherMethods M=new OtherMethods();
     pasdata.LoadFile_id(id);
    // pasFile.dataShow.MoveLast();
     txtName_Pas_Data.setText(pasdata.getValue(pasdata.Name));
     txtID_Pas_Data.setText(pasdata.getValue(pasdata.ID));
ClnDateBirth_Pas_Data.setDate(M.GetStringVal(pasdata.getValue(pasdata.DateBirth)));
   txtGender_Pas_Data.setText(pasdata.getValue(pasdata.Gender));
    txtAge_Pas_Data.setText(pasdata.getValue(pasdata.Age));
    txtJob_Pas_Data.setText(pasdata.getValue(pasdata.Job));
    txtAddress_Pas_Data.setText(pasdata.getValue(pasdata.Address));
    txtMob_Pas_Data.setText(pasdata.getValue(pasdata.Mob));
    txtGov_Pas_Data.setText(pasdata.getValue(pasdata.Gov));
    txtMarital_Status_Pas_Data.setText(pasdata.getValue(pasdata.Status));
    txtHome_Phone_Pas_Data.setText(pasdata.getValue(pasdata.HomePhone));
    txtWeight_Pas_Status.setText(pasdata.getValue(pasdata.Weight));
    txtHeight_Pas_Status.setText(pasdata.getValue(pasdata.Height));
    txtSugar_Pas_Status.setText(pasdata.getValue(pasdata.Suger));
    txtBlood_Pas_Status.setText(pasdata.getValue(pasdata.Blood));
    txtHymoglopin_Pas_Status.setText(pasdata.getValue(pasdata.hymoglobin));
 String Rsee,LSee,see;
 see=pasdata.getValue(pasdata.See);
 String TotalSee[]=see.split("/");
 Rsee=TotalSee[0].substring(2);
 LSee=TotalSee[1].substring(2);
 txtRight_Eye_Pas_Status.setText(Rsee);
 txtLeft_Eye_Pas_Status.setText(LSee); 

 
 
 
 
   
 }
 
 void LoadPasFile(String file_id) throws SQLException, ParseException{
        pasFile.LoadFile_id(file_id);

  txtNum_Vist_otherData.setText(pasFile.getValue(pasFile.NumVist));
 txtSrv_Type_otherData.setText(pasFile.getValue(pasFile.TypeService));
 txtExam_Type_otherData.setText(pasFile.getValue(pasFile.ExamType));
 txtTreat_Doc_otherData.setText(pasFile.getValue(pasFile.TreatDoctor));
txtCnvrt_Doc_otherData.setText(pasFile.getValue(pasFile.ConvertDoctor));
txtExam_Value_otherData.setText(pasFile.getValue(pasFile.ExamValue));
txtTime_Vist_otherData.setText(pasFile.getValue(pasFile.TimeVisit));
txtDetails_OtherData.setText(pasFile.getValue(pasFile.StatueDetails));
txtDrugs_otherData.setText(pasFile.getValue(pasFile.Drugs));
txtTreat_Rquest1_otherData.setText(pasFile.getValue(pasFile.TreatRequest1));
 }
 
 void LoadPasRevenue(String id) throws SQLException, ParseException{
 /* OtherMethods o=new OtherMethods();
pasRevenue.LoadFile_id(id);
pasRevenue.setControl(txtPationt_ID,txtPasiont_Name,txtExamDate, txt_ExamType, txt_ExamValue, txt_pasValue,  txt_InsValue, txt_ope, txt_Consum, txt_srv, txt_Total, txt_percent);
 pasRevenue.LoadinControl();
 */
txt_pasValue.setText(pasRevenue.getRevenu(pasRevenue.pasValue, Pas_id ));
txt_ExamValue.setText(pasRevenue.getRevenu(pasRevenue.ExamValue, Pas_id));
 txt_InsValue.setText(pasRevenue.getRevenu(pasRevenue.InsValue, Pas_id));
 txt_ope.setText(pasRevenue.getRevenu(pasRevenue.operation, Pas_id));
txt_Consum.setText(pasRevenue.getRevenu(pasRevenue.Consum, Pas_id));
txt_srv.setText(pasRevenue.getRevenu(pasRevenue.Srv, Pas_id));
txt_Total.setText(pasRevenue.getRevenu(pasRevenue.Total, Pas_id));
 txt_percent.setText(pasRevenue.getRevenu(pasRevenue.Percent, Pas_id));
 }

    private void txtName_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_Pas_DataActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_Pas_DataActionPerformed

    private void txtJob_Pas_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJob_Pas_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJob_Pas_DataActionPerformed

    private void txtTreat_Rquest1_otherDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreat_Rquest1_otherDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreat_Rquest1_otherDataActionPerformed

    private void pnl_VisitComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnl_VisitComponentShown

    }//GEN-LAST:event_pnl_VisitComponentShown

    private void Tble_pasRevenue1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tble_pasRevenue1MouseClicked

    }//GEN-LAST:event_Tble_pasRevenue1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker ClnDateBirth_Pas_Data;
    private javax.swing.JLabel LblAddress_Pas_Data;
    private javax.swing.JLabel LblAge_Pas_Data;
    private javax.swing.JLabel LblBlood_Pas_Status;
    private javax.swing.JLabel LblCnvrt_Doc_otherData;
    private javax.swing.JLabel LblDateBirth_Pas_Data;
    private javax.swing.JLabel LblDate_Vist_otherData;
    private javax.swing.JLabel LblDetails_OtherData;
    private javax.swing.JLabel LblDrugs_otherData;
    private javax.swing.JLabel LblExam_Type_otherData;
    private javax.swing.JLabel LblExam_Value_otherData;
    private javax.swing.JLabel LblGender_Pas_Data;
    private javax.swing.JLabel LblGov_Pas_Data;
    private javax.swing.JLabel LblHeight_Pas_Status;
    private javax.swing.JLabel LblHome_Phone_Pas_Data;
    private javax.swing.JLabel LblHymoglopin_Pas_Status;
    private javax.swing.JLabel LblID_Pas_Data;
    private javax.swing.JLabel LblJob_Pas_Data;
    private javax.swing.JLabel LblLeft_Eye_Pas_Status;
    private javax.swing.JLabel LblLst_dateVist_otherData;
    private javax.swing.JLabel LblMarital_Status_Pas_Data;
    private javax.swing.JLabel LblMob_Pas_Data;
    private javax.swing.JLabel LblName_Pas_Data;
    private javax.swing.JLabel LblNum_Vist_otherData;
    private javax.swing.JLabel LblPas_Status;
    private javax.swing.JLabel LblRight_Eye_Pas_Status;
    private javax.swing.JLabel LblSearch_ID_Pas_Data;
    private javax.swing.JLabel LblSet_Data;
    private javax.swing.JLabel LblSrv_Type_otherData;
    private javax.swing.JLabel LblSugar_Pas_Status;
    private javax.swing.JLabel LblTimeVist_otherData;
    private javax.swing.JLabel LblTraet_Rquest_otherData;
    private javax.swing.JLabel LblTreat_Doc_otherData;
    private javax.swing.JLabel LblTreat_Request_otherData;
    private javax.swing.JLabel LblTreat_Requst_otherData;
    private javax.swing.JLabel LblTreat_Rquest_otherData;
    private javax.swing.JLabel LblWeight_Pas_Status;
    private javax.swing.JLabel Lbl_OtherData;
    private javax.swing.JLabel Lbl_Search_Name_pas_Data;
    private javax.swing.JTable Tble_Show_dataFile;
    private javax.swing.JTable Tble_pasRevenue1;
    private projict_Class.ALable aLable10;
    private projict_Class.ALable aLable11;
    private projict_Class.ALable aLable2;
    private projict_Class.ALable aLable3;
    private projict_Class.ALable aLable4;
    private projict_Class.ALable aLable5;
    private projict_Class.ALable aLable6;
    private projict_Class.ALable aLable7;
    private projict_Class.ALable aLable8;
    private projict_Class.ALable aLable9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlPas_Status;
    private javax.swing.JPanel pnlSearch_Pas_Data;
    private javax.swing.JPanel pnl_Main_Data;
    private javax.swing.JPanel pnl_Other_Data;
    private javax.swing.JPanel pnl_Visit;
    private javax.swing.JTextField txtAddress_Pas_Data;
    private javax.swing.JTextField txtAge_Pas_Data;
    private javax.swing.JTextField txtBlood_Pas_Status;
    private javax.swing.JTextField txtCnvrt_Doc_otherData;
    private javax.swing.JTextField txtDate_Vist_otherData;
    private javax.swing.JTextField txtDetails_OtherData;
    private javax.swing.JTextField txtDrugs_otherData;
    private projict_Class.TxTf txtExamDate;
    private javax.swing.JTextField txtExam_Type_otherData;
    private javax.swing.JTextField txtExam_Value_otherData;
    private javax.swing.JTextField txtGender_Pas_Data;
    private javax.swing.JTextField txtGov_Pas_Data;
    private javax.swing.JTextField txtHeight_Pas_Status;
    private javax.swing.JTextField txtHome_Phone_Pas_Data;
    private javax.swing.JTextField txtHymoglopin_Pas_Status;
    private javax.swing.JTextField txtID_Pas_Data;
    private javax.swing.JTextField txtJob_Pas_Data;
    private javax.swing.JTextField txtLeft_Eye_Pas_Status;
    private javax.swing.JTextField txtMarital_Status_Pas_Data;
    private javax.swing.JTextField txtMob_Pas_Data;
    private javax.swing.JTextField txtName_Pas_Data;
    private javax.swing.JTextField txtNum_Vist_otherData;
    private javax.swing.JTextField txtNxt_dateVist_otherData;
    private javax.swing.JTextField txtRight_Eye_Pas_Status;
    private javax.swing.JTextField txtSearchID_Pas_Data;
    private javax.swing.JTextField txtSearchName_Pas_Data;
    private javax.swing.JTextField txtSrv_Type_otherData;
    private javax.swing.JTextField txtSugar_Pas_Status;
    private javax.swing.JTextField txtTime_Vist_otherData;
    private javax.swing.JTextField txtTreat_Doc_otherData;
    private javax.swing.JTextField txtTreat_Request2_otherData;
    private javax.swing.JTextField txtTreat_Rquest1_otherData;
    private javax.swing.JTextField txtTreat_Rquest3_otherData;
    private javax.swing.JTextField txtTreat_Rquest4_otherData;
    private javax.swing.JTextField txtWeight_Pas_Status;
    private projict_Class.TxTf txt_Consum;
    private projict_Class.TxTf txt_ExamType;
    private projict_Class.TxTf txt_ExamValue;
    private projict_Class.TxTf txt_InsValue;
    private projict_Class.TxTf txt_Total;
    private projict_Class.TxTf txt_ope;
    private projict_Class.TxTf txt_pasValue;
    private projict_Class.TxTf txt_percent;
    private projict_Class.TxTf txt_srv;
    // End of variables declaration//GEN-END:variables
}
